### ISSUE TITLE
[Bug]: 导出后内容为空

### ISSUE THREAD

**Issue by mattheliu** [Wsine/feishu2md#101]
### 问题描述

导出后内容为空，只有标题
![图片](https://github.com/Wsine/feishu2md/assets/102272920/4413fb65-1d51-4e73-a377-f3d9d588e8bd)
### 飞书文档链接

https://deepthought.feishu.cn/wiki/C39ZwiWxMij0zdkCf86cYWmVnMd?from=from_copylink

### 期望的 markdown 格式

```markdown
github markdown格式
```

**Comment by Wsine** [comment]
大概知道问题在哪了

在飞书文档的富文本格式里，Heading 也可以折叠 🤕 

但是，在 markdown 的格式里，heading 怎么做折叠呢

建议去掉飞书文档的折叠再尝试导出

**Comment by mattheliu** [comment]
感谢大佬的回复，我待会尝试一下
但是有个问题是，他的富文本格式是标题的类型：一级标题二级标题，如果取消的话那怎么设置标题大小呢

**Comment by Wsine** [comment]
看起来是飞书文档那边更改了强制层级，等我有时间了更新一下代码。

**Comment by Wsine** [comment]
@mattheliu 新的修复版本已更新，欢迎使用。
