### ISSUE TITLE
[Bug]: 始终提示：Invalid feishu/larksuite/allowHost URL format

### ISSUE THREAD

**Issue by Mayer123321** [Wsine/feishu2md#105]
### 问题描述

按照文档的操作内容进行了对应操作后，提示：Invalid feishu/larksuite/allowHost URL format
![WechatIMG15311](https://github.com/Wsine/feishu2md/assets/148830419/4b82de75-d739-4a7d-9ed0-f17dcebf2f5d)

### 飞书文档链接

https://bytedance.larkoffice.com/wiki/FF2QwOHHZiA6DZkPknycOglWnde?from=from_copylink

### 期望的 markdown 格式

```markdown
# title
## 二级title
table
```

**Comment by Wsine** [comment]
你的完整命令是什么？

`feishu2md dl --allowHost "bytedance.larkoffice.com" "https://bytedance.larkoffice.com/wiki/FF2QwOHHZiA6DZkPknycOglWnde?from=from_copylink"`

**Comment by Mayer123321** [comment]
> 你的完整命令是什么？
> 
> `feishu2md dl --allowHost "bytedance.larkoffice.com" "https://bytedance.larkoffice.com/wiki/FF2QwOHHZiA6DZkPknycOglWnde?from=from_copylink"`

我写的是：feishu2md dl  文档链接

**Comment by Wsine** [comment]
> `feishu2md dl --allowHost "bytedance.larkoffice.com" "https://bytedance.larkoffice.com/wiki/FF2QwOHHZiA6DZkPknycOglWnde?from=from_copylink"`

@Mayer123321  Try this

**Comment by Wsine** [comment]
这个域名和网址应该是字节内部私有的吧，我也无法进行访问进行测试，不知道如何帮忙

**Comment by Wsine** [comment]
@Mayer123321 我又研究了一下，使用如下命令可以便捷下载

```bash
feishu2md dl --allowHost "larkoffice.com" "https://bytedance.larkoffice.com/wiki/FF2QwOHHZiA6DZkPknycOglWnde?from=from_copylink"
```

**Comment by Wsine** [comment]
新版本 v2.2.0 去除了 allowHost 的手动参数，会自动处理。

**Comment by huiguangx** [comment]
这问题一直存在啊 https://y03l2iufsbl.feishu.cn/docx/XfL4di0YNosjoGxjfMtcGKKPnkg?from=from_copylink


![Image](https://github.com/user-attachments/assets/763a4c94-fd69-4790-a830-b4db6afeac51)
