### ISSUE TITLE
[Feat]: 能不能添加同时下载多个飞书文档的功能

### ISSUE THREAD

**Issue by metatwin** [Wsine/feishu2md#107]
### 问题描述

1. 目前通过feishu2md可以下载飞书文档了，但是对于大量文档下载还是过于繁琐。
2. 而且只能下载“互联网上获得链接的人可阅读”的文档，对于其他的文档还是无法下载
![image](https://github.com/Wsine/feishu2md/assets/96966752/25b0a161-50f5-435c-b7dd-02fdcfb595cd)

### 飞书文档链接

https://metatwin.feishu.cn/docx/VuuRdj8yVo4v4xxaBcAcr7UInJb?from=from_copylink

### 期望的 markdown 格式

```markdown
# 请添加一键下载多份文档功能
# 解决因文档权限而无法下载的BUG
```

**Comment by Wsine** [comment]
标题与描述不符合。

针对标题，有些人想要下载多个不同地方的文档，有些人想要下载同一个文件夹下的文档，实在是难以覆盖这样的多样性。之前我的建议都是让用户自己写个脚本来实现的。

针对描述的内容，目前我发现个人飞书可以用主账号（非测试账号）申请权限并自我审核通过了。如果使用主账号的 API key 可以不需要公共链接。

**Comment by metatwin** [comment]
呢要是用的是企业飞书，且账户非管理员情况下应该怎么办呢？
我自己创建的测试APP管理员也不开放文档阅、下载读权限。

**Comment by Wsine** [comment]
试试沟通。

**Comment by metatwin** [comment]
大佬，请问多文档下载可有方法？目前，需要导出的文件有点多，一个个转换有点繁琐。😕

**Comment by Wsine** [comment]
已完成 #125
