### ISSUE TITLE
能否支持导出支持原始图片url

### ISSUE THREAD

**Issue by RoyLR** [Wsine/feishu2md#109]
### 问题描述

能不能支持直接导出的markdown图片链接是飞书文档的原始url？

### 飞书文档链接

无

### 期望的 markdown 格式

```markdown
无
```

**Comment by Wsine** [comment]
没理解，请详细阐述需求。

**Comment by Wsine** [comment]
两周无更新回复，暂时关闭issue，有问题请再打开。
