### ISSUE TITLE
关于导出后表格等样式丢失

### ISSUE THREAD

**Issue by wangzhongl** [Wsine/feishu2md#11]
你好，我发现我导出后，表格会丢失，一些样式也会出现问题，请问是什么问题啊 
这是我要导出的地址 https://dkk1seyfgz.feishu.cn/docx/doxcnb48pOheRq53JX3JFXKN2mb
生成后变成了这个样子：
https://eworldgroup.feishu.cn/docx/doxcnhzbk9Q2f5PVv4G8CAua9yf

**Comment by Wsine** [comment]
因为还没实现表格的内容解析

**Comment by wangzhongl** [comment]
请问后续会更新实现嘛 我发现那些序列号的蓝色样式及图片也都没能解析

**Comment by Wsine** [comment]
表格是会更新的，markdown 本身的语法也支持，但要思考一下怎么实现，比较飞书的 OpenAPI 把它分为两块了。

序列号的样式需要具体问题具体分析，如果可以希望给出样例和期望的 markdown 表达。

**Comment by Wsine** [comment]
没有访问权限，建议直接贴图飞书文档到这里，然后用代码块描述期望的 markdown 格式。

很多富文本格式，虽然 markdown 本身语法支持嵌套 html，但是暂时没有计划支持，暂时只支持原生 markdown 语法。

**Comment by wangzhongl** [comment]
![image](https://user-images.githubusercontent.com/103638520/182552800-a5827bd6-460d-459e-975f-92df9d170201.png)
![image](https://user-images.githubusercontent.com/103638520/182552897-312b073a-5960-42c2-bad5-0aa03e264d6f.png)

**Comment by wangzhongl** [comment]
您好 你是说飞书文档本身的markdown语法是有自己定义的规则嵌套进去的对吗，我的初衷就是想飞书文档咋样，复制出来到其他markdown也是咋样的 哈哈

**Comment by Wsine** [comment]
我新开了一个 issue 来讨论有序列表的问题。这个问题请专注在表格的问题本身。@wangzhongl

**Comment by Wsine** [comment]
> 您好 你是说飞书文档本身的markdown语法是有自己定义的规则嵌套进去的对吗，我的初衷就是想飞书文档咋样，复制出来到其他markdown也是咋样的 哈哈

markdown 是一个纯文本格式，建议先去了解一下 markdown 的语法。原理上不可实现，就像你无法把一个网页复制到 Word 里一样。

**Comment by Naist4869** [comment]
> > 您好 你是说飞书文档本身的markdown语法是有自己定义的规则嵌套进去的对吗，我的初衷就是想飞书文档咋样，复制出来到其他markdown也是咋样的 哈哈
> 
> markdown 是一个纯文本格式，建议先去了解一下 markdown 的语法。原理上不可实现，就像你无法把一个网页复制到 Word 里一样。

Pandoc 可以

**Comment by wangzhongl** [comment]
什么可以
