### ISSUE TITLE
能否增加导出Lark文档的功能？

### ISSUE THREAD

**Issue by Ignareo** [Wsine/feishu2md#110]
### 问题描述

Lark URL的格式形如`https://rfh6a41zvkb.sg.larksuite.com/docx/B8mTdiaH7oLP5XxXiJ3lLNheg6g?from=from_copylink`
中间夹了一个注册邮箱的域名(`.sg`)，最后加了`?from=from_copylink`

目前使用feishu2md来导出Lark时，报错如下：
Invalid feishu/larksuite/allowHost URL format

====================

Report the following if it is a bug

panic: Invalid feishu/larksuite/allowHost URL format

goroutine 1 [running]:
github.com/Wsine/feishu2md/utils.CheckErr({0x12fba40, 0xc000008af8})
        /github/workspace/utils/common.go:19 +0x106
main.handleDownloadCommand({0xc000016180?, 0xc000241bf8?}, 0x17be900)
        /github/workspace/cmd/download.go:28 +0x71
main.main.func3(0xc00025e580)
        /github/workspace/cmd/main.go:75 +0xab
github.com/urfave/cli/v2.(*Command).Run(0xc00011f9e0, 0xc00025e3c0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/command.go:163 +0x583
github.com/urfave/cli/v2.(*App).RunContext(0xc000214680, {0x12fe470?, 0x18141c0}, {0xc00005a080, 0x3, 0x4})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:313 +0xaa5
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main()
        /github/workspace/cmd/main.go:82 +0x5e5

### 飞书文档链接

https://rfh6a41zvkb.sg.larksuite.com/docx/B8mTdiaH7oLP5XxXiJ3lLNheg6g?from=from_copylink

### 期望的 markdown 格式

```markdown
Na
```

**Comment by Wsine** [comment]
其实一直都有 larksuite 的支持，只不过你这个网址里多了 sg 是第一次见。我发了一个新版 v2.2.0，已本地测试通过，如仍有问题可以重新打开该 issue，谢谢。
