### ISSUE TITLE
[Bug]: 文档名包含'/'时输出报错

### ISSUE THREAD

**Issue by leeyx03** [Wsine/feishu2md#117]
### 问题描述

比如文档名为： bug测试-2024/04/28
config设置title as filename=True, 报错： The system cannot find the path specified.
貌似是代码会把文件名作为多层路径了。
所以想着是否可以增加指定输出文件名的功能，来规避类似的问题

### 飞书文档链接

https://hglookn1vs.feishu.cn/docx/NuvTdpcKdoG81UxGMI3cmAohnrf

### 期望的 markdown 格式

```markdown
无
```

**Comment by leeyx03** [comment]
自己改了下，麻烦大佬看看能不能合并下
 https://github.com/Wsine/feishu2md/pull/118

**Comment by Wsine** [comment]
我能问一下，为什么需要文档名包含 “/” 字符吗？

而且既然已知文档名包含“/”了，为什么还刻意设置title as filename=True？

解决方案我也不是很理解，为什么要在命令里增加参数手动指定文件名？手动改一下文件名复杂度再下载差不多吧？再不济，把文件名里面的非法字符转义了会不会更好呢？

**Comment by leeyx03** [comment]
> 我能问一下，为什么需要文档名包含 “/” 字符吗？用“-”是不是也能表达日期呢？
> 
> 而且既然已知文档名包含“/”了，为什么还刻意设置title as filename=True？
> 
> 解决方案我也不是很理解，为什么要在命令里增加参数手动指定文件名？手动改一下文件名复杂度再下载差不多吧？再不济，把文件名里面的非法字符转义了会不会更好呢？

这个问题是批量下载飞书文档时发现的，当前的使用方式是python调用执行命令行，有好多历史文档是包含“/”，自己去改的话不太现实；
因为知识库中目录结构和文档数量都很多，设置title as filename=True 也是为了方便查找；
希望可以解惑

**Comment by Wsine** [comment]
那我建议PR的解决方案修改为转义文件名里面的非法字符会更好，这样你就不用在每条命令里输入一遍新文件名了，自动化效率会更高。

**Comment by H0wAway** [comment]
windows新建一个文件，都会提示文件名不能包含下列任何字符: "\/:*?"<>"

**Comment by Wsine** [comment]
已统一替换非法字符为下划线
