### ISSUE TITLE
[Bug]: 下载exe后，配置好secret，无法下载他人的文档，报404。但是在线版可以下载其他人的文档，请问是什么原因？

### ISSUE THREAD

**Issue by lowols** [Wsine/feishu2md#119]
### 问题描述

![image](https://github.com/Wsine/feishu2md/assets/11570684/89952eb0-3131-4fe8-aba8-dd5c40361c0c)

### 飞书文档链接

https://lisxpq12rl7.feishu.cn/wiki/QkOzwr3gIiv8eTkKngTc6Lv6nlf

### 期望的 markdown 格式

```markdown
#
```

**Comment by Wsine** [comment]
wiki 文档可能还是旧版飞书文档，需要用该工具的旧版本下载，详见 Readme

**Comment by Wsine** [comment]
两周没有新的回复，暂时关闭issue
