### ISSUE TITLE
[Feat]: 有计划将feishu2md发布到homebrew上吗？

### ISSUE THREAD

**Issue by PRESIDENT810** [Wsine/feishu2md#122]
### 问题描述

目前想本地使用feishu2md的话，要么从源码构建，要么手动下载二进制文件并移动到PATH下，并且要去系统设置里面关闭安全设置（macOS平台下），如果能直接brew install feishu2md立马使用的话用户体验会非常好

我个人很愿意帮忙完成这项feature

### 飞书文档链接

N/A

### 期望的 markdown 格式

```markdown
N/A
```

**Comment by Wsine** [comment]
这个功能好像已经有热心网友提交了。

https://formulae.brew.sh/formula/feishu2md

**Comment by Wsine** [comment]
已有实现，先关闭issue了
