### ISSUE TITLE
[Bug]: 图片无法导出

### ISSUE THREAD

**Issue by yuzhou3996** [Wsine/feishu2md#124]
### 问题描述

原文档中存在图片，导出后失败
![image](https://github.com/Wsine/feishu2md/assets/31774471/e075d69d-6af9-423b-aaaf-951b480f322e)

### 飞书文档链接
https://xx6kcz1s3jh.feishu.cn/docx/B31mdzUJAoKuVnxDSjUcjiWsnle?from=from_copylink

### 期望的 markdown 格式

```markdown
我也不知道
```

**Comment by Wsine** [comment]
请先检查权限设置
