### ISSUE TITLE
[Bug]: 2.3版本更新后config失效

### ISSUE THREAD

**Issue by SnowyLake** [Wsine/feishu2md#126]
### 问题描述

如题所述, 替换回2.2版本后config恢复正常, 应该可以百分百复现

### 飞书文档链接

None

### 期望的 markdown 格式

```markdown
None
```

**Comment by Wsine** [comment]
我刚刚试了一下，并没有复习，你能给出你的运行环境和复现的步骤吗？

**Comment by SnowyLake** [comment]
如下图所示, 分别在2.2/2.3版本下同一文档进行相同操作, 结果2.3版本工具config未生效:
测试文档: https://dp68itxgy8.feishu.cn/docx/XSp3dOtKdoxxi4xOE2pcfUUZnOc
![bugreport_v2_2](https://github.com/Wsine/feishu2md/assets/57230205/e14c1c4e-6139-4186-b81e-e459a33500c0)
![bugreport_v2_3](https://github.com/Wsine/feishu2md/assets/57230205/5f330a5e-26f5-4644-a063-5b55ffd4ea62)

**Comment by Wsine** [comment]
噢，我懂了，你是说`title_as_filename`这个配置项失效了，而不是 config 命令无法生成和修改配置文件了

问题已确认，我有空去追踪看看

**Comment by SnowyLake** [comment]
output下的几个配置应该是都失效了, 你看img也没有像2.2版本那样被归到static文件夹下
