### ISSUE TITLE
[Feat]: 请求添加功能: 导出图片文件夹命名与md文件名一致

### ISSUE THREAD

**Issue by SnowyLake** [Wsine/feishu2md#127]
### 问题描述

期望实现:
```
// config.json
"output": {
//...
"image_dir_name_as_filename": true,
  }
```
输出文件结构:
- Root
  - file_name.md
  - file_name
    - imgA.png
    - imgB.png

### 飞书文档链接

None

### 期望的 markdown 格式

```markdown
None
```

**Comment by Wsine** [comment]
我能问问这个实现的需求来源吗？和“static”文件夹对比

**Comment by SnowyLake** [comment]
在管理静态网站时会将每个md文件使用的图片归属到各自的文件夹中 这样方便删改

**Comment by CharlesHAO77** [comment]
可以自己写代码二次开发，解压完之后重命名

**Comment by Wsine** [comment]
没有更多的讨论，暂时关闭issue
