### ISSUE TITLE
[Bug]: docker的方式报错

### ISSUE THREAD

**Issue by jkcn18** [Wsine/feishu2md#130]
### 问题描述

使用docker的方式，点击下载后，报错
<img width="486" alt="飞书报错" src="https://github.com/user-attachments/assets/79bb88ad-2735-4d39-bc12-cb1bca713cb0">
docker logs:
Captured document token: 
2024/07/15 04:32:40 error: invalid json: 404 page not found, err: invalid character 'p' after top-level value
2024/07/15 04:32:40 http: panic serving 192.168.120.3:53443: error: invalid json: 404 page not found, err: invalid character 'p' after top-level value
goroutine 182 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1873 +0xb9
panic({0xdd6a40?, 0xc0001bbf20?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
log.Panicf({0xf98329?, 0x1f4?}, {0xc0005e5818?, 0xc000491950?, 0x0?})
	/usr/local/go/src/log/log.go:439 +0x65
main.downloadHandler(0xedf200?)
	/feishu2md/web/download.go:65 +0x52a
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00051c340, 0xc000304500)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620 +0x65b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00051c340, {0x1171390?, 0xc00047e2a0}, 0xc000304400)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576 +0x1dd
net/http.serverHandler.ServeHTTP({0xc00030a180?}, {0x1171390?, 0xc00047e2a0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2943 +0x8e
net/http.(*conn).serve(0xc0000ad7a0, {0x1172108, 0xc00054f080})
	/usr/local/go/src/net/http/server.go:2014 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3091 +0x5cb

### 飞书文档链接

没有

### 期望的 markdown 格式

```markdown
没有
```

### (可选)更多信息

没有

**Comment by Wsine** [comment]
没有足够的信息追溯错误
