### ISSUE TITLE
[Bug]: 批量下载飞书文档时可能会触发飞书 API 的 frequency limit

### ISSUE THREAD

**Issue by zhangdingding** [Wsine/feishu2md#137]
### 问题描述

批量下载飞书文档时可能会触发[飞书 API 的请求频率限制](https://open.feishu.cn/document/server-docs/api-call-guide/frequency-control)，`feishu2md` 展示的错误码如下：

```
request Drive#GetDocxDocument failed: code: 99991400, msg: request trigger frequency limit
```

建议增加 `rateLimit` 配置参数，以避免触发频率限制问题。

### 飞书文档链接

N/A

### 期望的 markdown 格式

```markdown
N/A
```

**Comment by Wsine** [comment]
频率限制默认已经添加了

https://github.com/Wsine/feishu2md/blob/58f876a4c0d3679dbac3eeaebdcf5a6660b243f5/core/client.go#L20-L28

当然还有一种情况是飞书团队又调小了频率限制，这就要去调查了

**Comment by zhangdingding** [comment]
好的，感谢回复。我会去做进一步的调查，有结果了也会反馈给大家

**Comment by zhangdingding** [comment]
查阅了飞书开放平台的相关文档，其中：

- [云空间概述](https://open.feishu.cn/document/server-docs/docs/drive-v1/introduction)中提到了"以下云空间中涉及到修改节点状态或改变节点结构类接口不支持并发调用，且调用频率上限为 5 QPS，10000 次/天”的调用限制：
![feishu1](https://github.com/user-attachments/assets/a4a50670-295d-4341-b37b-b9cb8a7a1195)
- [获取文档基本信息](https://open.feishu.cn/document/server-docs/docs/docs/docx-v1/document/get)中提到了“单个应用调用频率上限为每秒 5 次”
![feishu2](https://github.com/user-attachments/assets/0514cda7-48d7-425b-af3d-eb959496c59e)
- [下载文件](https://open.feishu.cn/document/server-docs/docs/drive-v1/download/download)中提到“该接口调用频率上限为 5 QPS”
![feishu3](https://github.com/user-attachments/assets/b494a45e-b6d5-4c58-b72f-1ccd96e70c36)
- [下载素材](https://open.feishu.cn/document/server-docs/docs/drive-v1/media/download)中提到“该接口调用频率上限为 5 QPS，10000 次/天”
![feishu4](https://github.com/user-attachments/assets/e3f40289-1080-4cd8-b1e5-cab805512f36)

由文档可以得知，文档类接口（含文件、素材下载）的 Rate Limit 是 5 QPS，但从我查阅飞书应用的后台日志来看，获取文档的接口确实超出了 5 QPS：

![log](https://github.com/user-attachments/assets/15531bd1-9bd1-43f2-826c-1f06581f026b)

虽然上面提到了代码中是写了 `lark.WithApiMiddleware(lark_rate_limiter.Wait(5, 5))` 的（我对 `golang` 不熟悉），但从结果来看确实没生效

**Comment by anc95** [comment]
@zhangdingding 
> 虽然上面提到了代码中是写了 lark.WithApiMiddleware(lark_rate_limiter.Wait(5, 5)) 的（我对 golang 不熟悉），但从结果来看确实没生效

我把代码 download 下来，本地改成1，1 好使了

**Comment by Wsine** [comment]
已根据建议调低了并发数。
