### ISSUE TITLE
[Feat]: 是否能够增加对画板内容的支持，万分感谢

### ISSUE THREAD

**Issue by innocentshen** [Wsine/feishu2md#138]
### 问题描述

期望能够增加对画板内容的导出
![image](https://github.com/user-attachments/assets/3f7176e1-b95c-43c0-ae28-ab5f61734c02)

### 飞书文档链接

无

### 期望的 markdown 格式

```markdown
无
```

**Comment by Wsine** [comment]
请参考：#94
