### ISSUE TITLE
[Bug]: Wiki 同一个路径下多个文档难以区分

### ISSUE THREAD

**Issue by A1phaN** [Wsine/feishu2md#140]
### 问题描述

考虑以下 Wiki 目录：
```yaml
1:
  - 1-1
  - 1-2
  - 1-3:
    - 1-3-1
```
这里 `1-1` `1-2` `1-3` 都会在路径 `1` 下面存储为 `{OBJ_TOKEN}.md`，非常难以区分，我猜想可能是因为文档名称不方便直接做为文件名（非法字符 / 重名），但是文件夹名称已经用了，是否可以套用相同的解决方案，或者单独生成一个包含所有文档名称和路径的 yaml 文件之类

### 飞书文档链接

https://w8ct7civ9u.feishu.cn/wiki/VY00wAk0gikhHckw67Kc75cwnDf?from=from_copylink

### 期望的 markdown 格式

```markdown
非 markdown 生成问题
```

**Comment by Wsine** [comment]
在配置文件里修改 TitleAsFilename 可以把标题作为文档名称

https://github.com/Wsine/feishu2md/blob/9506373536513817424b8771d17602147f73d3d5/core/config.go#L35

**Comment by A1phaN** [comment]
感谢解答
