### ISSUE TITLE
403 forBidden

### ISSUE THREAD

**Issue by penlinux** [Wsine/feishu2md#15]
触及盲区了

```bash
2022/08/06 22:43:26 request Drive#GetDocxDocument failed: code: 1770032, msg: forBidden
```

**Comment by Wsine** [comment]
见 Readme，重新配置 token，飞书修改了权限的规则

**Comment by penlinux** [comment]
授权倒是做了，如果没配置权限确实跟 #16 问题一样。。。不想折腾了，也许是我的IP被拉黑了

**Comment by Wsine** [comment]
@penlinux 也许是你忘记分享飞书文档为公开可见了

**Comment by penlinux** [comment]
> @penlinux 也许是你忘记分享飞书文档为公开可见了

好吧，管理设置了不能公开分享...

**Comment by freestylefly** [comment]
> 见 Readme，重新配置 token，飞书修改了权限的规则
https://qd1njuv5qj.feishu.cn/docx/Z2CrddTpao7PDaxMK7lcm3snnVe

这个公开分享的也是403，不知道是啥原因呢
