### ISSUE TITLE
飞书文档无法导出，提示No permission

### ISSUE THREAD

**Issue by PrinceOfAndroid** [Wsine/feishu2md#16]
PS D:\tool\feishu2md-amd64\windows> D:\tool\feishu2md-amd64\windows\feishu2md.exe https://cz7occ727w.feishu.cn/docs/doccnBIDVGv679assLSq2M91bgh
Captured doc token: doccnBIDVGv679assLSq2M91bgh
2022/08/08 16:29:00 request Drive#GetDriveDocContent failed: code: 99991672, msg: No permission

**Comment by Wsine** [comment]
ref to #15
