### ISSUE TITLE
end of JSON input 问题

### ISSUE THREAD

**Issue by WayneTian-42** [Wsine/feishu2md#2]
已经提前运行过`config`指令，并且在json中修改了id和secret，图片文件夹没有修改
尝试导出md文件时遇到如下报错
![image](https://user-images.githubusercontent.com/52881295/170265011-63cc67c6-6ce3-49e1-a8c7-14503c486c14.png)

**Comment by Wsine** [comment]
可能是 JSON 文件的编码问题。删掉配置文件重新用命令生成，然后用 VSCODE 这类多编码支持的编辑器修改配置文件看看。

**Comment by WayneTian-42** [comment]
> 

我是用VSCODE打开的，编码方式有要修改的吗
![image](https://user-images.githubusercontent.com/52881295/170280355-c481a9c4-94e8-46ff-9f1f-250af0f94a5f.png)

**Comment by RavenLite** [comment]
遇到了相同问题哈

**Comment by AmintaCCCP** [comment]
同样的问题，只改了app_id和app_secret

**Comment by Wsine** [comment]
比较奇怪，我下载了最新版本重新生成了配置文件。然后用 vscode 打开，换行符是 LF 类型。

![image](https://user-images.githubusercontent.com/8842278/170414648-2e3a6741-9b29-4561-8937-11c4a767a7fb.png)

**Comment by Wsine** [comment]
@WayneTian-42 你图中 JSON 的图标也有一个 x 的标识，说明 JSON 格式不对，所以程序读 JSON 的时候会报错 end of JSON input

**Comment by WayneTian-42** [comment]
改成这样也是相同报错
![image](https://user-images.githubusercontent.com/52881295/170463064-b411d6e1-af27-4059-a2f0-2470dfeafc52.png)

**Comment by Wsine** [comment]
问题找到了。当提供的下载链接包含`#headers`后缀的时候，lark 库的内部处理会报错。

错误 URL：
```
https://oaztcemx3k.feishu.cn/docs/doccnrOvzeQ8BSnfsXj8jwJHC3c#gkgML5
```

正确 URL：
```
https://oaztcemx3k.feishu.cn/docs/doccnrOvzeQ8BSnfsXj8jwJHC3c
```

同时 [Release](https://github.com/Wsine/feishu2md/releases/tag/v0.1.2) 中提供了一个 v0.1.2 版本使用正则表达式提取 docToken，能同时handle上述两种情况

**Comment by WayneTian-42** [comment]
> 关于 JSON 格式的问题应该已经解决了，后面如果有报错 `invalid memory address or nil pointer dereference` 是由其它问题造成的，请移步 #3 已有解决方案。
> 
> Release 中更新了一版，也可以先试试。

使用了最新版，还是相同问题，链接没有`#header`
![image](https://user-images.githubusercontent.com/52881295/170510150-ef5aa472-2f5b-485a-ad2b-e1cd0fd7cc02.png)

**Comment by WayneTian-42** [comment]
> 关于 JSON 格式的问题应该已经解决了，后面如果有报错 `invalid memory address or nil pointer dereference` 是由其它问题造成的，请移步 #3 已有解决方案。
> 
> Release 中更新了一版，也可以先试试。

使用新版后仍然遇到该问题，链接也没有`#header`
![image](https://user-images.githubusercontent.com/52881295/170510852-fe7445f2-46d6-4065-a0d2-ea1b4c870093.png)

**Comment by Wsine** [comment]
@WayneTian-42 请先确保你的飞书文档公开链接本身可以被可读访问

**Comment by DoctorDream** [comment]
> 

我也是遇到了这个问题，不管是windows还是linux，都是无法解析json输入

**Comment by Wsine** [comment]
@DoctorDream 如果可以的话，请提供脱敏的文档供测试

**Comment by DoctorDream** [comment]
https://z2janszcad.feishu.cn/docs/doccnVyZIpSJ9YMqFpJ5L7Wnrpd
你可以用这个链接试一下，不过我还是怀疑还是json解析的问题，或许在json读取格式中固定编码格式会有帮助？（很抱歉，我是python开发者，只能根据我的经验给出一点不成熟的建议）

**Comment by Wsine** [comment]
@DoctorDream 在我的测试环境中能成功下载文档。

如果你读了 SSPAI 的文章过来的，你会发现我也是新手 lol 。在 golang 语言中有标准的处理方式将 struct 和 json 双向绑定，生成配置文件和读取配置文件使用的是这种方式，理论上不会出现编码格式问题。但由于中途需要人为修改配置文件，各种不同的编辑器行为会带来差异，或许在命令行中生成配置文件的时候就可以加入 API 令牌信息。

另一方面，JSON 解析问题也有可能是解析飞书文档本身带来的。如果你能看到`Captured doc token`这个字眼，说明读取配置文件环节已经成功了。但是，如果飞书文档本身不是公开链接，那么 API 返回的 json 信息也无法被反序列化到 struct 中，因此会造成解析问题，建议都排查一下。或许加入文档链接有效性校验是一个方法。

**Comment by xysyige** [comment]
@Wsine 您好，我也遇到了这个问题，已经出现了 `Captured doc token` 字样，也显示了JSON文件配置中的app_id和app_secret，应该就是你说的读取配置文件成功了，但是飞书返回的信息有问题导致了这个错误。

但是我也确认了，分享的链接是可以在浏览器隐身模式访问的。

除了链接的问题外，在创建应用这一步有什么特殊的操作吗？  比如是否要开通一些权限之类的。

谢谢

**Comment by Wsine** [comment]
@xysyige 权限的话默认的可阅读权限就可以了。

对于有能力的用户，可以自行测试中间可能的错误，[如何手动验证工作流](https://github.com/Wsine/feishu2md/wiki/%E5%A6%82%E4%BD%95%E6%89%8B%E5%8A%A8%E9%AA%8C%E8%AF%81%E5%B7%A5%E4%BD%9C%E6%B5%81)

如果方便的话，也可以提供脱敏的文档供测试。

**Comment by xysyige** [comment]
我的问题解决了，这里记录下我解决的方法。

1、导出markdown功能，底层调用了飞书 [获取文档富文本](https://open.feishu.cn/document/ukTMukTMukTM/uUDM2YjL1AjN24SNwYjN) 这个API，这个API是需要申请权限的，否则调不通，就会报 `end of JSON input` 这个错误。

2、创建一个企业，信息可以随便填，然后在企业下创建应用，申请上述链接中 `权限要求` 中的任一项，发布应用，在企业后台审核通过。

3、在配置文件中，配置企业账户下应用的 `app_id` 和 `app_secret`。

4、平时使用还是用飞书个人版，这时分享出的链接，就可以正常导出markdown文件了。

创建企业是因为，我没找到个人账户创建的应用申请权限后如何审核，界面显示需要管理员审核，但是我没找到审核的后台。
创建企业后，当前账户默认就是管理员，可以看到企业后台，有应用审核的入口。
