### ISSUE TITLE
文档中有图片，连接的时候报权限问题

### ISSUE THREAD

**Issue by echogqq** [Wsine/feishu2md#23]
当doc中有图片的时候，要求的权限已经全部开通, 但是报问题 request Drive#GetDocxDocument failed: code: 1770032, msg: forBidden。

事实上尝试把云文档的所有权限都开通，也同样是报一样的问题。

**Comment by Wsine** [comment]
是否有脱敏文档能提供进行问题复现

**Comment by Wsine** [comment]
一周没有新的回复，暂时关闭 issue，如仍有问题，可以重新打开。

**Comment by zhanghad** [comment]
我的文档在个人用户的账户中，遇到同样问题，需要公开文档访问链接才可以下载。请问如何能够在不公开文档的情况下下载文档？（我用这个工具做飞书文档的备份）

**Comment by Wsine** [comment]
> 我的文档在个人用户的账户中，遇到同样问题，需要公开文档访问链接才可以下载。请问如何能够在不公开文档的情况下下载文档？（我用这个工具做飞书文档的备份）

不太清楚，这个超过了该工具覆盖的范畴。

**Comment by erge66** [comment]
能否导出只有查看权限的，别人分享的文档

**Comment by Wsine** [comment]
> 能否导出只有查看权限的，别人分享的文档

可以啊

**Comment by erge66** [comment]
遇到同样的问题，目前文档是在组织内可以访问，互联网用户是不可以访问的，但是我的用户是拥有阅读访问权限，也报这个错

**Comment by Wsine** [comment]
> 遇到同样的问题，目前文档是在组织内可以访问，互联网用户是不可以访问的，但是我的用户是拥有阅读访问权限，也报这个错

可能你用的是飞书测试账号的 API Token，如果组织能审核通过你的 API 权限申请，你不必使用测试 API Token

**Comment by DanielZhao1990** [comment]
- 使用用户token（ User access token）可以正常调用接口
- 使用应用token（Tenant access token）报错，报错为1770032,当前调用方式属于应用token
文档权限分为两种，一种是用户权限，一种是应用权限。
https://open.feishu.cn/document/server-docs/docs/faq#2431c595
4. 添加应用为文档协作者[完成解决]
需要应用开启机器人能力。
需要 文档所有者、知识库管理员 或 其他协作者 为资源 添加文档应用。文档、电子表格、多维表格、知识库 通过云文档 Web 页面右上方「...」->「...更多」-> 「添加文档应用」入口添加。

**Comment by Spute** [comment]
> 遇到了同样的报错： request Drive#GetDocxDocument failed: code: 1770032, msg: forBidden 确认应用所需要的权限都已开通 后发现将文档链接分享改为“互联网上获得链接的人可阅读”即可正常下载，默认的“组织内获得链接的人可阅读”则报错，与文档内是否包含图片无关。

之前设置成“互联网上获得链接的人可阅读”，不用实名的，现在必须要实名。。。

**Comment by 1Wizzy** [comment]
- 如果飞书开放平台中feishu2md的权限使用tenant_access_token
   - 需要通过云文档页面右上方「...」→「...更多」→「添加文档应用」为应用添加权限
   - 确保文档未启用密码保护等额外安全设置
- 如果飞书开放平台中feishu2md的权限使用user_access_token
   - 需要通过文档「分享」功能为当前用户添加权限
