### ISSUE TITLE
飞书网络访问超时

### ISSUE THREAD

**Issue by seeping007** [Wsine/feishu2md#24]
环境信息：
- MacBook Pro (16-inch, 2019)，macOS Monterey 12.3.1

问题：
- 执行 feishu2md config --appId ... 并没有在对应目录生成config.json文件（不过 feishu2md config 能输出配置json信息）
- 执行 feishu2md <url> 提示：Post "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by Wsine** [comment]
是否有运行截图可以提供？

**Comment by seeping007** [comment]
> 是否有运行截图可以提供？

- 第一个问题不影响。不过已经设置了环境变量，在默认路径和指定路径下均找不到config.json
- 第二个问题可能是网络原因（运行结果如问题描述），目前ok。是否可以配置超时时间？

**Comment by Wsine** [comment]
默认配置路径是 `~/.config/feishu2md/config.json`，如果没有的话会自动创建，如无特别设置该主目录是有权限正常创建文件和文件夹的。如无该文件或没有正确配置，会影响工具正常运行。

延长网络请求的超时时间需要通过修改代码实现增加配置项，但默认超时时间已能满足绝大部分需求，建议检查网络原因。如在外网可以考虑使用 larksuite.

如果相同用户也遇到该问题，请投票该功能让我看到。

**Comment by Wsine** [comment]
似乎没有更多用户遇到这样的问题，暂时关闭，如仍有问题，请重新打开
