### ISSUE TITLE
M1的mac使用哪个版本呢？

### ISSUE THREAD

**Issue by jun9100** [Wsine/feishu2md#25]
M1的mac使用哪个版本呢？
菜鸟搞了半天不知道怎么启用。

**Comment by jun9100** [comment]
并将相应平台的 feishu2md 可执行文件放置在 PATH 路径中即可。
这个PATH是可以自己指定的吗？
是需要先安装go环境，然后再自行配置吗？

**Comment by jun9100** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x8b7aa0]
这个软件能在虚拟机你运行么？

**Comment by jun9100** [comment]
Last login: Sat Oct  8 16:40:07 on ttys000
ron@Rons-MacBook-Pro ~ % go version
go version go1.19.2 darwin/arm64
ron@Rons-MacBook-Pro ~ % feishu2md -h
zsh: killed     feishu2md -h

**Comment by Wsine** [comment]
mac M1 的属于 arm，请下载[feishu2md-v1.1.0-darwin-arm64.tar.gz](https://github.com/Wsine/feishu2md/releases/download/v1.1.0/feishu2md-v1.1.0-darwin-arm64.tar.gz)

不需要安装 go 的运行环境，这是编译型软件的优势。

PATH 可以自己指定 `export PATH=$PATH:<your_custom_path>`

也可以 `echo $PATH` 查看一下现有的 PATH 路径，随便找一个放进去

如问题能解决，请自行关闭 issue

祝好

**Comment by jun9100** [comment]
谢谢。
