### ISSUE TITLE
LaTeX转出符号是%而并非是$

### ISSUE THREAD

**Issue by caozeze** [Wsine/feishu2md#28]
若我们在飞书文档里用了LaTeX，应该是需要添加$$$$，但是最终导出的时候，$都变成了%
![image](https://user-images.githubusercontent.com/52779586/199623768-b1cf6311-7827-433f-93a2-ec2cd8b25f7c.png)

**Comment by Wsine** [comment]
PR #29 修复了该问题。

新的可执行文件可以从这里下载 https://github.com/Wsine/feishu2md/releases/tag/v1.2.2

如有问题可以在此回复

**Comment by Wsine** [comment]
issue 已经解决了，如仍有此问题，可再开启
