### ISSUE TITLE
请问支持飞书个人版吗？

### ISSUE THREAD

**Issue by 0604hx** [Wsine/feishu2md#30]
如题，谢谢！

**Comment by Wsine** [comment]
试试不就知道了

**Comment by 0604hx** [comment]
> 试试不就知道了

飞书个人版不支持，因为个人版无法授权给`自建应用`读取文档。

另外，需要将自建应用设置为文档的协作者才能正常导出 markdown（操作说明见：https://open.feishu.cn/document/ukTMukTMukTM/uczNzUjL3czM14yN3MTN）

**Comment by Wsine** [comment]
我一直在用个人版，请参考 README 配置。

思维导图导出暂无实现，如有兴趣可参与实现 PR。
