### ISSUE TITLE
飞书新版文档支持

### ISSUE THREAD

**Issue by Wsine** [Wsine/feishu2md#4]
由于飞书新版文档使用了全新的 API 接口和数据结构，上游 lark 项目还没有更新，因此暂时无法支持下载新版文档为 markdown。

**Comment by sos233** [comment]
https://yitanger.feishu.cn/docx/doxcnDAfsVce0m20UBtT5d2Hj4f

**Comment by Wsine** [comment]
@sos233 是的，新版文档的链接 URL 的中间都是 docx，旧版文档是 docs

**Comment by qingsf1** [comment]
您好，以下这种文档地址下载报错，是因为wiki这种文档不支持吗？

feishu2md  https://yvzhu1joh4.feishu.cn/wiki/wikcn2aBpGw3GSYEKaNsF8hn6jb#U1PHKV
panic: Invalid feishu/larksuite URL containing docToken

**Comment by Wsine** [comment]
@sos233 已支持新版文档，欢迎试用。

**Comment by sos233** [comment]
@Wsine  效果挺好 👍

**Comment by sos233** [comment]
@Wsine   https://yitanger.feishu.cn/docs/doccnnQqOLMf5rJ7YU7VbguRA6L

**Comment by Wsine** [comment]
> @Wsine 这个文档报错了 https://yitanger.feishu.cn/docs/doccnnQqOLMf5rJ7YU7VbguRA6L json: cannot unmarshal number 384.5866968844363 into Go struct field DocImageItem.body.blocks.gallery.imageList.width of type int

这个应该是上游 lark 的错误，建议报告给 lark

**Comment by ischt** [comment]
2022/12/04 20:20:43 request Drive#GetDocxDocument failed: code: 99991672, msg: Access denied. One of the following scopes is required: [docx:document, docx:document:readonly]

请问如何解决

**Comment by xpc0938** [comment]
> 2022/12/04 20:20:43 request Drive#GetDocxDocument failed: code: 99991672, msg: Access denied. One of the following scopes is required: [docx:document, docx:document:readonly]
> 
> 请问如何解决

我也遇到了，block到这里了，不知道如何解决？

**Comment by xpc0938** [comment]
我block在这儿了：
2022/12/28 12:16:10 request Drive#GetDocxDocument failed: code: 1770032, msg: forBidden

**Comment by wy-z** [comment]
> 我block在这儿了： 2022/12/28 12:16:10 request Drive#GetDocxDocument failed: code: 1770032, msg: forBidden

建议先排查下飞书文档上的权限配置有没有问题
1. 是否添加文档应用
<img width="334" alt="image" src="https://user-images.githubusercontent.com/4213483/209756950-e99e891a-a917-471f-9588-2b62a33de181.png">
2. 文档应用权限配置是否正确

**Comment by 9694368924** [comment]
感谢开发者

**Comment by kamalkk** [comment]
> 限配置有没有问题 @xpc0938

嗨，这个文件解决了吗？
