### ISSUE TITLE
Crash in MacOS 13.0

### ISSUE THREAD

**Issue by highsense** [Wsine/feishu2md#40]
**问题描述**
执行任意feishu2md命令，例如：feishu2md --help
均会得到一个如下错误：
[1]    82459 segmentation fault  feishu2md --help

**To Reproduce**
是否有可公开访问的脱敏链接以供测试。
是

**期望的 markdown 格式**
----------
请描述在这里
----------

**报错的截图**
![image](https://user-images.githubusercontent.com/1118454/210690545-a12d5e9f-e644-409c-8d30-9aec392ca522.png)

**更多信息**
操作系统：MacOS 13.0
芯片：Intel
安装包：feishu2md-v1.3.3-darwin-amd64.tar.gz

**Comment by wy-z** [comment]
Mac 的话看下“隐私与安全性”里有没有提示

**Comment by highsense** [comment]
> 

没有看到有提示

**Comment by wy-z** [comment]
![image](https://user-images.githubusercontent.com/4213483/211861715-bc7ffbe2-6c28-4799-ae00-b8dc303d39f0.png)

@Wsine Mac 的安装包，在 MacOS M1 13.0 下似乎都都问题

**Comment by Wsine** [comment]
> @Wsine Mac 的安装包，在 MacOS M1 13.0 下似乎都有问题

唔，那我周末看看，但我没有 M1 芯片的 mac，到时候再想想办法。

**Comment by highsense** [comment]
老铁们，我在macbook intel芯片下会报segmentation fault，跟M1芯片crash不是一个问题吧？

**Comment by Wsine** [comment]
> 老铁们，我在macbook intel芯片下会报segmentation fault，跟M1芯片crash不是一个问题吧？

大概率是同一个问题。目前的进展，我确定了手动打包能够在 M1 MacOS 13.1 下正常运行。应该还是和打包有关系。

**Comment by Wsine** [comment]
我周末基本上定位到问题是在压缩上面，目前我们项目采用 `upx` 工具压缩可执行文件，但在 macos 13.0 和 macos 13.1 上面均测试无法正确执行，但在 macos 12.x 上面可以。

upx 仓库也有相关的 issue，详见 https://github.com/upx/upx/issues/612

我们目前有两种解决方案：
1. 在自动化工具中禁用 macos 的可执行文件的压缩，等待 upx 适配或 macos 后续系统修复后再重新添加回来。
2. 手动打包 macos 的可执行文件共享

由于我在用 Linux 服务器用该工具做自动化，这方面想听听你 @wy-z  的意见。

**Comment by wy-z** [comment]
> 我周末基本上定位到问题是在压缩上面，目前我们项目采用 `upx` 工具压缩可执行文件，但在 macos 13.0 和 macos 13.1 上面均测试无法正确执行，但在 macos 12.x 上面可以。
> 
> upx 仓库也有相关的 issue，详见 [upx/upx#612](https://github.com/upx/upx/issues/612)
> 
> 我们目前有两种解决方案：
> 
> 1. 在自动化工具中禁用 macos 的可执行文件的压缩，等待 upx 适配或 macos 后续系统修复后再重新添加回来。
> 2. 手动打包 macos 的可执行文件共享
> 
> 由于我在用 Linux 服务器用该工具做自动化，这方面想听听你 @wy-z 的意见。

我倾向先禁用 MacOS 的 Upx 压缩～维护，变更成本都低些，对用户影响也不大～

**Comment by Wsine** [comment]
@highsense @wy-z 

Hello, 我重新编译了一个预发布版本 v1.3.4 暂时修复了该问题，在次邀请两位使用其作为日常的工具，如有问题可以继续反馈。

下载地址：https://github.com/Wsine/feishu2md/releases/tag/v1.3.4

一段时间后，如没有更多的问题我会将这个版本转为最新版本。

**Comment by highsense** [comment]
> @highsense @wy-z
>
> Hello, 我重新编译了一个预发布版本 v1.3.4 暂时修复了该问题，在次邀请两位使用其作为日常的工具，如有问题可以继续反馈。
>
> 下载地址：https://github.com/Wsine/feishu2md/releases/tag/v1.3.4
>
> 一段时间后，如没有更多的问题我会将这个版本转为最新版本。
谢谢老铁，v1.3.4版本在我电脑上可以正常运行了
