### ISSUE TITLE
文档中包含流程图，期望也能自动下载

### ISSUE THREAD

**Issue by wumindc** [Wsine/feishu2md#45]
**问题描述**
文档中包含使用飞书文档绘制的流程图，转成markdown下载时，流程图内容丢失

**To Reproduce**
https://rinmo68hgn.feishu.cn/docx/ZX0edbXPboTQQexWN15cjct6n6g

**期望的 markdown 格式**
包含流程图，讲流程图下载为图片之类的均可

**报错的截图**
无

**更多信息**
无

**Comment by Wsine** [comment]
这个需求我看了一下似乎做不到，因为飞书的 OpenAPI 没有提供这样的信息。

流程图和 UML 图都属于 Diagram 类，但这个类里面只有一个 enum 类型表示其为流程图和 UML 而已。

https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/document-docx/docx-structure#6a09da6
