### ISSUE TITLE
引用类文本，导出后样式丢失

### ISSUE THREAD

**Issue by wumindc** [Wsine/feishu2md#46]
**问题描述**
引用类文本，导出后样式丢失

**To Reproduce**
https://rinmo68hgn.feishu.cn/docx/ZX0edbXPboTQQexWN15cjct6n6g

**期望的 markdown 格式**
导出后保留 文本引用样式

**报错的截图**
- 飞书文档截图
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/19991659/216214811-25685e66-74d4-4a75-941b-d790b57d183a.png">

- 导出markdown内容截图

<img width="574" alt="image" src="https://user-images.githubusercontent.com/19991659/216215101-5780c361-2e19-4d0b-8b81-194fa60ff676.png">

**更多信息**
无

**Comment by Wsine** [comment]
@wy-z 我实现了一下这个需求，不用重复做了。
