### ISSUE TITLE
panic: Invalid feishu/larksuite URL containing docToken

### ISSUE THREAD

**Issue by JingYu-Kylin** [Wsine/feishu2md#5]
panic: Invalid feishu/larksuite URL containing docToken

goroutine 1 [running]:
main.checkErr(...)
        /home/runner/work/feishu2md/feishu2md/utils.go:10
main.main.func1(0xc0002ca000)
        /home/runner/work/feishu2md/feishu2md/main.go:116 +0x105
github.com/urfave/cli/v2.(*App).RunContext(0xc00024dba0, {0x17be2d0, 0xc000012030}, {0xc0000423c0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322 +0x7a8
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main()
        /home/runner/work/feishu2md/feishu2md/main.go:122 +0x156

**Comment by Wsine** [comment]
the title already tells what is the problem.
