### ISSUE TITLE
mbp 非M1 下载运行报错

### ISSUE THREAD

**Issue by liqian5365** [Wsine/feishu2md#50]
**问题描述**
下载的是feishu2md-v1.3.4-darwin-arm64.tar.gz
解压后运行一直报错

**To Reproduce**
是否有可公开访问的脱敏链接以供测试。

**期望的 markdown 格式**
----------
请描述在这里
----------

**报错的截图**
![image](https://user-images.githubusercontent.com/16534570/219240727-12dc7f0c-c300-4608-8c54-4834f8c06419.png)

**更多信息**
如有

**Comment by wy-z** [comment]
https://github.com/Wsine/feishu2md/releases/download/v1.4.0/feishu2md-v1.4.0-darwin-amd64.tar.gz 下载 darwin amd64

**Comment by liqian5365** [comment]
> https://github.com/Wsine/feishu2md/releases/download/v1.4.0/feishu2md-v1.4.0-darwin-amd64.tar.gz 下载 darwin amd64

闪退了

**Comment by Wsine** [comment]
@liqian5365 方便提供一下报错信息吗？

**Comment by liqian5365** [comment]
> @liqian5365 方便提供一下报错信息吗？

没有报错了，你看下我的是不是操作步骤有问题
![image](https://user-images.githubusercontent.com/16534570/219257049-ffe74754-6c63-493d-8de9-4f4cfb036120.png)

**Comment by Wsine** [comment]
`export PATH=$PATH:/Users/liqian/Downloads/feishu2md-v1.4.0-darwin-amd64`

**Comment by liqian5365** [comment]
> export PATH=$PATH:/Users/liqian/Downloads/feishu2md-v1.4.0-darwin-amd64

可以了，非常感谢。
