### ISSUE TITLE
批量下载云空间指定文件夹下的云文档

### ISSUE THREAD

**Issue by liqian5365** [Wsine/feishu2md#53]
**问题描述**
请清晰具体地描述你的问题。

**To Reproduce**
是否有可公开访问的脱敏链接以供测试。

**期望的 markdown 格式**

----------
复制文件夹的链接然后下载文件夹列表，现在的需求是需要一个一个链接复制，列表多的话比较麻烦
----------

**报错的截图**
如有

**更多信息**
如有

**Comment by Wsine** [comment]
没有理解。什么是「文件夹的链接」？什么是「文件夹列表」?

希望认真对待，好好提问。

**Comment by liqian5365** [comment]
> 没有理解。什么是「文件夹的链接」？什么是「文件夹列表」?
> 
> 希望认真对待，好好提问。


非常抱歉描述的不准确，如下图所示
![image](https://user-images.githubusercontent.com/16534570/220498954-74d5d457-43be-4f38-acb0-49b9f4c017dc.png)
比如我复制的是红色圈起来的文件夹链接，我希望下载的是内部绿色圈起来的子文件。不知道有没有描述清楚。

**Comment by Wsine** [comment]
我找到了 https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/list

你可以通过这个API先拿到链接列表，然后再分别下载
