### ISSUE TITLE
导出文档失败

### ISSUE THREAD

**Issue by chaos-zhu** [Wsine/feishu2md#56]
**问题描述**
导出内部文档，应用权限已给，暂无脱敏链接：
2023/03/16 15:42:54 request Drive#GetDriveDocContent failed: code: 95006, msg: Failed

**Comment by wy-z** [comment]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/4213483/225550527-29c09ce0-9df8-40ee-8078-7b0b9716f278.png">
url 错了？

**Comment by Wsine** [comment]
可能是文档的链接还没公开分享

参考这个情况 https://github.com/Wsine/feishu2md/issues/23#issuecomment-1461432723

**Comment by chaos-zhu** [comment]
已经公开了。下载docx的会出现这情况，md的正常

**Comment by Wsine** [comment]
我猜你想说的是 doc 正常，docx 报错，大概还是权限的问题。doc 和 docx 的权限开关是分开的。

参考 https://github.com/Wsine/feishu2md/issues/41
