### ISSUE TITLE
支持飞书中知识库的文档导出为markdown格式吗？

### ISSUE THREAD

**Issue by qingsf1** [Wsine/feishu2md#6]
您好，以下这种文档地址下载报错，是因为wiki这种文档不支持吗？

feishu2md https://yvzhu1joh4.feishu.cn/wiki/wikcn2aBpGw3GSYEKaNsF8hn6jb#U1PHKV
panic: Invalid feishu/larksuite URL containing docToken
![image](https://user-images.githubusercontent.com/32427358/175768587-0a656012-ed98-4838-b5ef-425cbb5310e0.png)

这种文档应该是飞书知识库的文档， 参考api地址  
https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/wiki-v2/space/list  获取知识空间列表

**Comment by Wsine** [comment]
这种暂时没有测试，后期新飞书文档API开发稳定后，我看看能不能也兼容了

**Comment by Wsine** [comment]
@qingsf1 我看了知识库的飞书 API，并没有能够返回内容的。因此不能实现，可以考虑自行全文复制到一个临时飞书文档然后使用该工具下载。
