### ISSUE TITLE
默认配置文件路径提示有误

### ISSUE THREAD

**Issue by Wsine** [Wsine/feishu2md#60]
> @willdla 你需要手动修改配置文件中的配置项。
> 
> 配置文件路径参考
> 
> 生成的配置文件路径为：
> 
> Windows: %AppData%/feishu2md/config.json
> 
> Linux: $XDG_CONFIG_HOME/feishu2md/config.json
> 
> Mac: $XDG_CONFIG_HOME/feishu2md/config.json
> 
> 如无配置 XDG_CONFIG_HOME 环境变量，则默认为 ~/.config 目录。
> 
> 相关配置项为 `TitleAsFilename` 默认为 false，可根据需求更改为 true

<img width="742" alt="image" src="https://user-images.githubusercontent.com/93644542/227402498-3deb99cf-b293-4ee4-9710-4f282ca3e1c3.png">

找不到这个文件夹 o(╥﹏╥)o.. 是不是出现了异常

_Originally posted by @willdla in https://github.com/Wsine/feishu2md/issues/26#issuecomment-1482133414_

**Comment by willdla** [comment]
对于我来说是在

```/Users/meow/Library/Application\ Support/feishu2md```

有需要的用户可以参考下
