### ISSUE TITLE
再现403 Forbidden

### ISSUE THREAD

**Issue by rovertang** [Wsine/feishu2md#62]
如题
可能原因：现在飞书文档需要将机器人添加为文档应用，才能下载了。
一个礼拜前没这个问题的。
今天遇到的。
最后是将机器人添加为文档应用后，可以下载了。
有点诡异，不知道其他同学有没有遇到。

**Comment by Wsine** [comment]
没有发现哎，刚刚测试了一下如常使用。而且该项目不是一个机器人应用，所以应该没有受到这样的限制。

**Comment by rovertang** [comment]
嗯。挺奇怪的。我现在就是必须添加机器人才可以。
另外，多说一句：是不是现在新建的文档都需要这么操作？可以试试新建的文档，老文档可能是不需要这个操作的。
最近已经试了两个文档了，看上去可能以后就是常态了，这必须添加机器人的话，确实有点麻烦了。

**Comment by Wsine** [comment]
我刚刚又新建文档测试了一下，不过也还是不需要。但我这个是个人飞书账号下的文档，我无法测试企业账号下的飞书文档。

**Comment by GQH123** [comment]
是不是图片的问题？文档里有些图片 url 是 blob:https://...，有些是 https://internal-api-drive-stream.feishu.cn/space/api/... ，像后面这种就会报 403，虽然文档权限都是开放的，浏览器无痕状态下也能正常访问。可能是请求头设置的有问题。
