### ISSUE TITLE
行内latex支持

### ISSUE THREAD

**Issue by wenjunyang** [Wsine/feishu2md#63]
**问题描述**
目前导出latex统一都是双$做边界符，导致行内的latex变成多行展示，辛苦看下能否解决这种问题。

**To Reproduce**
https://je8qmgybpk.feishu.cn/docx/CG2ddW9I0oyKyIxhZqOcwQlanhe

**期望的 markdown 格式**
----------
行内latex用单$做边界符
----------

**报错的截图**
原内容：

![image](https://user-images.githubusercontent.com/2840667/229879673-9c55f017-f9c6-4566-b8c1-bca6812bd4c5.png)

导出后的结果：
![image](https://user-images.githubusercontent.com/2840667/229879870-8b3d5bf1-e65b-42b9-9907-c0d692f7215c.png)

**更多信息**
无

**Comment by Wsine** [comment]
已增加相关实现，欢迎关注下一个版本的发布。

不过该注意的是，行内 Latex 的渲染不同的 Markdown 渲染器有不同的实现，请自行甄别。
