### ISSUE TITLE
如何进行批量导出呢

### ISSUE THREAD

**Issue by slowpy** [Wsine/feishu2md#64]
**问题描述**
如何进行批量导出呢，用了下单个导出很方便。很多时候目录结构很重要，能怎么按目录导出呢？

**To Reproduce**
是否有可公开访问的脱敏链接以供测试。

**期望的 markdown 格式**
----------
请描述在这里
----------

**报错的截图**
如有

**更多信息**
如有

**Comment by Wsine** [comment]
需要自行写脚本实现，暂时该工具没有计划这需求。
