### ISSUE TITLE
图片导出问题

### ISSUE THREAD

**Issue by zyglovepp** [Wsine/feishu2md#65]
不好意思问一下，我把md文件成功从飞书导出来，但是图片没有成功导出，md文件里面的img路径找不到图片。需要怎么做呢？

**Comment by Wsine** [comment]
请提供一份脱敏文档以供问题复现

**Comment by zyglovepp** [comment]
是我的问题，我移动了文件，导致相对路径错误了，不好意思，给您添麻烦了，感谢您的回复。

**Comment by zyglovepp** [comment]
对于有图片的飞书文档一定需要编辑权限吗？我能够成功导出没有图片的文档，也能导出有编辑权限的带图片的文档，但是导出只有阅读权限的带图片的飞书文档却报错：403forbidden。如果需要脱敏文档，请通知我。感谢您！

**Comment by Wsine** [comment]
还是提供一下脱敏文档吧，我好看看具体是什么问题。

**Comment by zyglovepp** [comment]
![微信图片_20230414124820](https://user-images.githubusercontent.com/70431495/231944482-622778b8-caa2-4e12-99fa-329c3165ab5f.png)
上图是在飞书已经打开了编辑权限
![微信图片_20230414124813](https://user-images.githubusercontent.com/70431495/231944502-98c2861d-d9be-42ee-9f05-7f5f63b8b979.jpg)
但是还是报错，之前是编辑权限下能够down下来的，现在连编辑权限打开了也不行了。应该是别的地方出问题了。
![a8d8ae409207de2109d9b75ce0b08c4](https://user-images.githubusercontent.com/70431495/231945088-2aef16ef-df98-40c6-a9e0-f0fba3423f8f.png)
上图是能成功down下另一个带图片的文档，排除是图片的问题，应该是这两个文档权限的问题。
![ScreenClip](https://user-images.githubusercontent.com/70431495/231946377-e56c7091-382d-4697-90d5-041cb7f75db1.png)
经过对比检验，最后判断应该是上图权限的问题，但是我这个文件暂时修改不了权限，所以只能到这了。
给您添麻烦了，不好意思。感谢您的答复。
