### ISSUE TITLE
open xxx.md: permission denied

### ISSUE THREAD

**Issue by freestylefly** [Wsine/feishu2md#68]
**问题描述**

mac m1 ，导出报错
**To Reproduce**
是否有可公开访问的脱敏链接以供测试。
https://u55dyuejxc.feishu.cn/docx/OQQjdF530oVTsIx24npcmPjMnge

**期望的 markdown 格式**
----------
测试导出md
----------

**报错的截图**

<img width="1002" alt="image" src="https://github.com/Wsine/feishu2md/assets/43960064/e18e600b-1f2a-462c-be61-857d5747f9a8">

**更多信息**
权限均已开放

**Comment by freestylefly** [comment]
已自行找到原因，我防止的path目录为：/usr/local/bin/，此文件夹默认普通用户只有只读权限，需要开启该文件所有访问权限即可
<img width="377" alt="image" src="https://github.com/Wsine/feishu2md/assets/43960064/410e6369-7527-4cd9-9b29-6744ed6f050b">

建议下载完后，迁移文档，并重新设置权限

**Comment by Wsine** [comment]
> **问题描述**
> 
> mac m1 ，导出报错 **To Reproduce** 是否有可公开访问的脱敏链接以供测试。 https://u55dyuejxc.feishu.cn/docx/OQQjdF530oVTsIx24npcmPjMnge
> 
> ## **期望的 markdown 格式**
> ## 测试导出md
> **报错的截图**
> 
> <img alt="image" width="1002" src="https://user-images.githubusercontent.com/43960064/240795218-e18e600b-1f2a-462c-be61-857d5747f9a8.png">
> **更多信息** 权限均已开放

API Token 已泄露，建议重置  Token。

**Comment by freestylefly** [comment]
> > **问题描述**
> > mac m1 ，导出报错 **To Reproduce** 是否有可公开访问的脱敏链接以供测试。 https://u55dyuejxc.feishu.cn/docx/OQQjdF530oVTsIx24npcmPjMnge
> > ## **期望的 markdown 格式**
> > ## 测试导出md
> > **报错的截图**
> > <img alt="image" width="1002" src="https://user-images.githubusercontent.com/43960064/240795218-e18e600b-1f2a-462c-be61-857d5747f9a8.png">
> > **更多信息** 权限均已开放
> 
> API Token 已泄露，建议重置 Token。

已做重置，谢谢提醒
