### ISSUE TITLE
请问是否支持下载别人的公开分享的链接为md文档呢

### ISSUE THREAD

**Issue by freestylefly** [Wsine/feishu2md#69]
请问是否支持下载别人的公开分享的链接为md文档呢

**Comment by Wsine** [comment]
支持的

**Comment by freestylefly** [comment]
我试了还是没权限呢？自己的没问题，但是别人只要设置了防幅值就不行

**Comment by Wsine** [comment]
> 我试了还是没权限呢？自己的没问题，但是别人只要设置了防幅值就不行

说明该公开分享仅可视不可下载，该工具不会解决这类问题，请自行联系文档拥有者

**Comment by freestylefly** [comment]
> 

好的，谢谢您
