### ISSUE TITLE
正式应用无法下载含有图片的文章，报错为403

### ISSUE THREAD

**Issue by ChunChunWeb** [Wsine/feishu2md#70]
**问题描述**
注意是在正式应用下无法下载含有图片的文章，在年前应该是可以的。
测试应用可以在测试公司进行下载，但正式应用无法在正式环境下载。

需要正式环境下的原因如下：
大多数文章在企业内部已经整理，需要进行下载。

**报错的截图**
![image](https://github.com/Wsine/feishu2md/assets/32215562/c0177643-39e7-414b-92eb-d8ce8d3c494f)

**更多信息**
经过测试发现如果含有图片就无法进行下载，非图片的文章可以进行下载。
云文档的所有权限都已经开放。
飞书改版前是可以的，可能是改版的原因？

**Comment by qingsf1** [comment]
遇到了相同的问题，想知道什么原因？怎么解决
D:\feishu2md-v1.4.0-windows-amd64>feishu2md https://xxxxx.feishu.cn/wiki/wikcnDuWrVDb91YlBFxi8JiFfM3
Captured document token: wikcnDuWrVDb91YlBFxi8JiFfM3
2023/05/26 13:36:57 request fail: 403 Forbidden

**Comment by ChunChunWeb** [comment]
> 遇到了相同的问题，想知道什么原因？有没有解决的思路? D:\feishu2md-v1.4.0-windows-amd64>feishu2md https://xxxxx.feishu.cn/wiki/wikcnDuWrVDb91YlBFxi8JiFfM3 Captured document token: wikcnDuWrVDb91YlBFxi8JiFfM3 2023/05/26 13:36:57 request fail: 403 Forbidden

害 我也不会go...

**Comment by qingsf1** [comment]
我的以上问题已经解决，现把问题原因和解决办法说明如下，希望对大家有所帮助
出现【 request fail: 403 Forbidden】问题的原因是wiki 知识空间权限设置问题
解决办法：以管理员身份登录飞书，选择右上角个人中心，在下拉框中选择【切换账号】先切换到要设置权限的账号
参考以下截图，选择【知识库】，进入【知识空间设置】页面，选择【安全设置】，把【是否允许可阅读的用户对空间内的页面内容进行复制、创建副本、打印、或导出（Word、PDF、图片等）？】选项设置成允许，即可解决【 403 Forbidden】的问题
![1](https://github.com/Wsine/feishu2md/assets/32427358/7d1f3e6f-d549-493a-957c-787f7b58908e)
![2](https://github.com/Wsine/feishu2md/assets/32427358/8e929229-5f1e-465d-be0c-6b75143487b6)
![3](https://github.com/Wsine/feishu2md/assets/32427358/d9edd40f-8eb8-4f1c-9de5-dbcfbba15b54)

**Comment by ChunChunWeb** [comment]
> 我的以上问题已经解决，现把问题原因和解决办法说明如下，希望对大家有所帮助 出现【 request fail: 403 Forbidden】问题的原因是wiki 知识空间权限设置问题 解决办法：以管理员身份登录飞书，选择右上角个人中心，在下拉框中选择【切换账号】先切换到要设置权限的账号 参考以下截图，选择【知识库】，进入【知识空间设置】页面，选择【安全设置】，把【是否允许可阅读的用户对空间内的页面内容进行复制、创建副本、打印、或导出（Word、PDF、图片等）？】选项设置成允许，即可解决【 403 Forbidden】的问题 ![1](https://user-images.githubusercontent.com/32427358/241173715-7d1f3e6f-d549-493a-957c-787f7b58908e.png) ![2](https://user-images.githubusercontent.com/32427358/241173726-8e929229-5f1e-465d-be0c-6b75143487b6.png) ![3](https://user-images.githubusercontent.com/32427358/241173731-d9edd40f-8eb8-4f1c-9de5-dbcfbba15b54.png)

谢谢你的解决方案，nice bro.

**Comment by ChunChunWeb** [comment]
![image](https://github.com/Wsine/feishu2md/assets/32215562/8768e78e-080e-4674-84f2-4d9f749fef0f)
刚刚测试的文章未带有图片，测试成功；但带有图片的仍报错为403，对应的权限设置已经打开

**Comment by qingsf1** [comment]
我这里导出是可以的，那你可以能是这里权限配置的问题
![4](https://github.com/Wsine/feishu2md/assets/32427358/6580a3b7-fcd8-40ed-9aae-53a75500ceab)

**Comment by Wsine** [comment]
已解决，关闭 issue

**Comment by ChunChunWeb** [comment]
> 我这里导出是可以的，那你可以能是这里权限配置的问题 ![4](https://user-images.githubusercontent.com/32427358/241198443-6580a3b7-fcd8-40ed-9aae-53a75500ceab.png)

我看你这张图还是测试企业运行，我的意思是正式应用是否可行。

**Comment by Wsine** [comment]
@ChunChunWeb 用飞书个人版的自建应用的话，正式版是不行的，因为无法自行审核权限配置问题。这个问题我问过客服了。

但是个人又可以自建企业，然后创建自建应用，这个时候就可以审核权限配置了。

我只能说飞书的游戏规则太复杂了。

**Comment by ChunChunWeb** [comment]
@Wsine 就很奇怪，我记得3月前我都是一直是正式版本，4月中旬左右吧开始不能使用。

**Comment by Wsine** [comment]
> @Wsine 就很奇怪，我记得3月前我都是一直是正式版本，4月中旬左右吧开始不能使用。

嗯，大概就是这个时候，他们更新飞书服务端加入了权限审核的要求。

**Comment by ChunChunWeb** [comment]
> > @Wsine 
大佬，能否添加忽略下载图片的选项呢

**Comment by Wsine** [comment]
> 大佬，能否添加忽略下载图片的选项呢

不是很理解这个需求，或许你可以展开说说。一般来说，不需要下载图片原文就不会上传图片；下载后也可以很容易全局正则匹配删除。

建议另开一个 issue 单独讨论。

**Comment by GQH123** [comment]
这问题现在还是存在的。文档里有些图片 url 是 blob:https://...，有些是 https://internal-api-drive-stream.feishu.cn/space/api/... ，像后面这种就会报 403，虽然文档权限都是开放的，浏览器无痕状态下也能正常访问。可能是较早的飞书 api 会用后面这种。403 可能是请求头设置有些问题。

**Comment by GQH123** [comment]
直接浏览器无痕访问图片链接会返回
```json
{"code":5,"message":"Login Required","data":null}
```
如果先打开文档，就可以按原链接正常访问图片

对比一下请求头，可以发现后者多设置了一些 cookies，应该是在访问文档的时候从服务器端得到的

**Comment by Wsine** [comment]
建议提供脱敏文档。

图片有几种可能，本地上传 / 网络地址引用 / 外部飞书文档。本地文档没有问题，网络地址如果没有设置防火墙一般也能下载，最大的问题是外部飞书文档，因为对方不一定开启了公开访问。

浏览器里我们可能用的是主账号访问，这个有外部文档的阅读权限。但下载器里我们用的是测试账号访问，这个没有权限。

不过也只是猜想，需要脱敏文档验证。如提供，欢迎重新打开 issue 。

**Comment by GQH123** [comment]
我暂时不太方便提供，不过浏览器无痕状态下是没有登入账号的，经常用来测试匿名/登出状态下看到的环境。文档也是正常公开的，这些都没有问题。

**Comment by Wsine** [comment]
> 直接浏览器无痕访问图片链接会返回
> 
> ```json
> {"code":5,"message":"Login Required","data":null}
> ```
> 
> 如果先打开文档，就可以按原链接正常访问图片
> 
> 对比一下请求头，可以发现后者多设置了一些 cookie，应该是在访问文档的时候从服务器端得到的

文档公开不代表图片也公开，虽然能在网页端预览，得具体问题具体分析。

**Comment by PRESIDENT810** [comment]
我可以提供一个脱敏测试用文档：https://qo0rpw16is.larksuite.com/docx/GCIfd7nsToPkDIxtDVmuPpAAsLb

报错信息：
```
GOROOT=/opt/homebrew/opt/go/libexec #gosetup
GOPATH=/Users/zhongkaining/go #gosetup
/opt/homebrew/opt/go/libexec/bin/go build -o /Users/zhongkaining/Library/Caches/JetBrains/GoLand2023.2/tmp/GoLand/___download . #gosetup
/Users/zhongkaining/Library/Caches/JetBrains/GoLand2023.2/tmp/GoLand/___download dl https://qo0rpw16is.larksuite.com/docx/GCIfd7nsToPkDIxtDVmuPpAAsLb
Captured document token: GCIfd7nsToPkDIxtDVmuPpAAsLb
request fail: 403 Forbidden

====================

Report the following if it is a bug

panic: request fail: 403 Forbidden

goroutine 1 [running]:
github.com/Wsine/feishu2md/utils.CheckErr({0x103225188, 0x14000312070})
        /Users/zhongkaining/GitHub/feishu2md/utils/common.go:22 +0x10c
main.downloadDocument({0x16d66379c?, 0x0?}, {0x102e61711, 0x2}, 0x0, 0x1400034e580)
        /Users/zhongkaining/GitHub/feishu2md/cmd/download.go:65 +0x3b4
main.handleDownloadCommand({0x16d66379c, 0x41}, 0x1036cc7f0)
        /Users/zhongkaining/GitHub/feishu2md/cmd/download.go:124 +0x78
main.main.func3(0x1400034e540)
        /Users/zhongkaining/GitHub/feishu2md/cmd/main.go:69 +0xac
github.com/urfave/cli/v2.(*Command).Run(0x1400031a000, 0x1400034e380)
        /Users/zhongkaining/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/command.go:163 +0x4a8
github.com/urfave/cli/v2.(*App).RunContext(0x140002d3ba0, {0x103227f70?, 0x103704360}, {0x14000194120, 0x3, 0x3})
        /Users/zhongkaining/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:313 +0x808
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/zhongkaining/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main()
        /Users/zhongkaining/GitHub/feishu2md/cmd/main.go:99 +0x79c

Process finished with the exit code 2

```
