### ISSUE TITLE
各种报错问题汇总排查

### ISSUE THREAD

**Issue by Wsine** [Wsine/feishu2md#71]
报错问题可能大家遇到的都差不多，可以先自行排查。

API 权限获取问题
- [request Drive#GetDocxDocument failed: code: 99991672, msg: Access denied.](https://github.com/Wsine/feishu2md/issues/41)

文档链接权限问题
- [request Drive#GetDocxDocument failed: code: 1770032, msg: forBidden.](https://github.com/Wsine/feishu2md/issues/23)

Token 有效性问题
- [request Drive#GetDriveDocContent failed: code: 95006, msg: Failed.](https://github.com/Wsine/feishu2md/issues/56)

组织知识库权限问题
- [request fail: 403 Forbidden.](https://github.com/Wsine/feishu2md/issues/70)

该 issue 持续更新，请勿回复

**Comment by frank8786** [comment]
文档转换时，提示invalid json: 404 page not found, err: invalid character 'p' after top-level value，请问是什么问题
![image](https://github.com/Wsine/feishu2md/assets/118524258/088f9722-a03c-4bdd-a51a-dfd7967bc22a)
