### ISSUE TITLE
对于正式版来说，当下载图片的时候未能正确下载图片，能否在遇到非关键问题时不直接退出

### ISSUE THREAD

**Issue by ChunChunWeb** [Wsine/feishu2md#73]
在 https://github.com/Wsine/feishu2md/issues/70 中，发现正式版本运行程序时遇到照片会有403的错误。此类错误并不重大影响程序运行，能否遇到非主体报错时不直接退出？
比如以下问题可能会导致文档导出有损坏，但不重大影响：
- 图片下载失败
- 表格导出失败
- 部分引用失败
- 等等

这样就算是权限部分问题也能够规避（其实主要还是想在正式应用中使用）。

谢谢大佬！

**Comment by Wsine** [comment]
虽然我不是很明白为什么这么执着于正式应用中使用，如果能说明一下会更好。

但是遇到图片下载失败时增加选项仅 report 但不 crash，还是没有问题的，我有空的时候加上。

**Comment by ChunChunWeb** [comment]
> 虽然我不是很明白为什么这么执着于正式应用中使用，如果能说明一下会更好。
> 

主要是因为在企业中有公共知识部分，大家都可以编写，然后做了个公司信息技术留存相关。如果仅是测试企业，一是数据不好搬迁，二是多人合作比较麻烦。

但是遇到图片下载失败时增加选项仅 report 但不 crash，还是没有问题的，我有空的时候加上。

> 但是遇到图片下载失败时增加选项仅 report 但不 crash，还是没有问题的，我有空的时候加上。
>

谢谢大佬！

**Comment by Wsine** [comment]
> 如果仅是测试企业，一是数据不好搬迁，二是多人合作比较麻烦。

按我的理解，其实没有必要开企业账号中的测试应用。文档可以照旧留在企业账号下，feishu2md 工具中的 API Token 可以来源于个人账户下的测试应用。

**Comment by Wsine** [comment]
@ChunChunWeb 最新的版本中新增了配置项`skip_img_download`

详见：[        SkipImgDownload bool   `json:"skip_img_download"`](https://github.com/Wsine/feishu2md/blob/cd6584521a2e5330746a1a2a6b7d35bdedffa350/core/config.go#L25)

**Comment by Wsine** [comment]
两周没有新回复，暂时关闭 issue，有问题再重新打开吧
