### ISSUE TITLE
飞书转markdown，有序列表编号错误

### ISSUE THREAD

**Issue by zkming9** [Wsine/feishu2md#74]
**问题描述**
有序列表存在正文，代码块，截图或者引用，或者嵌套二级有序或者无序列表时，后面的有序列表编号错误，缩进错误。

**To Reproduce**
是否有可公开访问的脱敏链接以供测试。
https://acoinfos.feishu.cn/docx/CNcddpyOFoTPx3xg76Jc3cz9nJg

**期望的 markdown 格式**
----------
请描述在这里
----------
有序列表编号能跟飞书文档保持完全一致。
有序列表里面的截图、正文、代码块、引用的缩进，在飞书转md时也要完全一致
**报错的截图**
![image](https://github.com/Wsine/feishu2md/assets/41888489/53b133e8-f5ef-4ac2-946d-f12e9394299b)

**更多信息**
有序列表转换时，新增了很多空行，需要删除

**Comment by zql365747776** [comment]
> 我在 [#12 (comment)](https://github.com/Wsine/feishu2md/issues/12#issuecomment-1203612865) 中回复过相关的问题。
> 
> 或许更好的解决办法是本地重建文档结构树，但那样的工作量比较大，需要等我非常有空的时候才会考虑。

我这边遇到了同样的问题，核心原因是 ParseDocxBlock 方法里面没有根据 block 的层级在前面增加空格缩进。

**Comment by Wsine** [comment]
@zql365747776 
我昨晚正好尝试了一下重构 Parser 根据 Tree 形式来做解析，可见 
https://github.com/Wsine/feishu2md/blob/dev/core/parser.go#L289-L336
如无意外的话，会在本月内发版。

> 核心原因是 ParseDocxBlock 方法里面没有根据 block 的层级在前面增加空格缩进。

我理解的核心原因是飞书 API 本身的报文里就没有 block 的层级，每一个 item 都是一个 block，参考报文可见
https://github.com/Wsine/feishu2md/blob/dev/testdata/testdocx.2.json

> 我目前在 ParseDocxBlock 方法的 switch case 前统一计算了前置空格，然后根据下面的各种 case 都不同的增加了前置缩进。
这样排出的markdown样式也更符合飞书上的原有层级格式。

我认为要规避格式的解析问题最重要的还是增加测试数据，如上面的 `testdocx.2.json` 和 `testdocx.2.md` 的对应关系。只有通过大量的测试才能避免这些 corner cases，这也是 v1 版本 feishu2md 工具没做好的点。

> 需要我提pr吗？

我个人是十分欢迎 PR 的，但由于目前比较专注于 v2 版本的重构，可能会建议你先尝试一下 dev 分支是否解决了你的问题，如果有更好的方案也可以提出，如果你也善于在这种情况下 PR 的话，我当然也是十分高兴的。

**Comment by zql365747776** [comment]
> 我理解的核心原因是飞书 API 本身的报文里就没有 block 的层级，每一个 item 都是一个 block，参考报文可见
> https://github.com/Wsine/feishu2md/blob/dev/testdata/testdocx.2.json

json 里面的 parentId 不是层级关系吗？
我就是根据你原来的递归在 blockMap 中找 parentId 来获取他的 level 的。
有了缩进 level，就貌似不需要 程序去解析 order 了。

**Comment by zql365747776** [comment]
> @zql365747776 我昨晚正好尝试了一下重构 Parser 根据 Tree 形式来做解析，可见 https://github.com/Wsine/feishu2md/blob/dev/core/parser.go#L289-L336 如无意外的话，会在本月内发版。
> 
> > 核心原因是 ParseDocxBlock 方法里面没有根据 block 的层级在前面增加空格缩进。
> 
> 我理解的核心原因是飞书 API 本身的报文里就没有 block 的层级，每一个 item 都是一个 block，参考报文可见 https://github.com/Wsine/feishu2md/blob/dev/testdata/testdocx.2.json
> 
> > 我目前在 ParseDocxBlock 方法的 switch case 前统一计算了前置空格，然后根据下面的各种 case 都不同的增加了前置缩进。
> > 这样排出的markdown样式也更符合飞书上的原有层级格式。
> 
> 我认为要规避格式的解析问题最重要的还是增加测试数据，如上面的 `testdocx.2.json` 和 `testdocx.2.md` 的对应关系。只有通过大量的测试才能避免这些 corner cases，这也是 v1 版本 feishu2md 工具没做好的点。
> 
> > 需要我提pr吗？
> 
> 我个人是十分欢迎 PR 的，但由于目前比较专注于 v2 版本的重构，可能会建议你先尝试一下 dev 分支是否解决了你的问题，如果有更好的方案也可以提出，如果你也善于在这种情况下 PR 的话，我当然也是十分高兴的。

我个人认为核心问题还是 block 的缩进问题，而不是有序列表的序号问题，序号只是缩进的表象问题。
我看了你 289 - 336 行的修改，还是在解决有序列表的序号问题。

飞书文档本身是有层级关系的，markdown 本身也是有层级关系的。
如果不处理缩进问题，一个图片，在飞书里面可能是左侧有两个缩进，但是经过程序转换，你的程序中没有给他加前置缩进，转出的markdown，就没有前置缩进，样式就和飞书上不完全一致了。

所以建议处理左侧缩进问题。左侧缩进问题处理好后，即便按照原来的逻辑，将所有的有序列表的数字都写成 1，后面的 lute 引擎也会将同层级所有的 1 给重新排序成正常序号。所以处理完缩进问题，序号问题自然解决了。

如果我还没有表述清除，你可以试试在飞书中输入
1.******
2.******
3.******

和

1.******
图片
2.******
引用等其他类型block
3.******

在两种case情况下，转换程序转换出来的效果。因为中间图片和引用没有正常缩进，顶在最左边了，打乱了原有的有序列表缩进规则，lute 就会认为这是一个新的有序列表，给转换成1.

如有问题，欢迎交流。

**Comment by Wsine** [comment]
我大概理解差异的点在哪里了。因为目前根据 parent-children 的 tree parser 其实已经有一定的实现了，而且 BulletList 和 OrderedList 两者的缩进也有实现，如果你细看 `indentLevel` 这个变量的话。

> 1.******
>（这里有一个缩进）图片
> 2.******
> （这里有一个缩进）引用等其他类型block
> 3.******

我理解现在的问题的关键是，是否需要将 indentLevel 的应用也扩展到其它所有的 block 类型。

我今晚试试增加更多的测试用例看看是否能够两头兼顾吧，如果能的话当然没有问题，不行的话再根据测试样例具体讨论。

**Comment by zql365747776** [comment]
> 我理解现在的问题的关键是，是否需要将 indentLevel 的应用也扩展到其它所有的 block 类型。

是的，核心在于 “是否需要将 indentLevel 的应用也扩展到其它所有的 block 类型。”
我就是这么解决的。

**Comment by Wsine** [comment]
> https://acoinfos.feishu.cn/docx/CNcddpyOFoTPx3xg76Jc3cz9nJg

@zkming9 该文档为非公开，无法访问。我最近发布了 2.0 版本，重构的时候也解决了这个问题，但还没做更多测试（本打算靠这个issue来测试的），或许你可以试试新版本，如果不行，欢迎 post 测试文档到这里。

**Comment by Wsine** [comment]
两周没有更新的回复，暂时关闭 issue，如仍有该问题，可重新打开
