### ISSUE TITLE
飞书 Sheet 类型没有导出成功

### ISSUE THREAD

**Issue by xmsz** [Wsine/feishu2md#76]
**问题描述**
![image](https://github.com/Wsine/feishu2md/assets/5879146/95f6c93d-5630-43de-b966-8946be4e592d)
![image](https://github.com/Wsine/feishu2md/assets/5879146/65a7a2e9-7839-481b-ac89-4ba507824491)

没有导出表格

**To Reproduce**
是否有可公开访问的脱敏链接以供测试。

https://china.feishu.cn/docx/KvtddjWdqo6Jb3x20SpcevD5nnh

**期望的 markdown 格式**
----------
请描述在这里
----------

**报错的截图**
如有

**更多信息**
如有

**Comment by JackiMa** [comment]
表格无法导出 + 1，[待导出的文档](https://a81isol8fe.feishu.cn/docx/ODBTdl5sMowg5zxwh2kcR6cQnKg)：

![image](https://github.com/Wsine/feishu2md/assets/96033062/e3971314-ae65-40b8-aea1-30f1b6c4a96f)

导出的文档：
![image](https://github.com/Wsine/feishu2md/assets/96033062/ba1a28c6-6295-42de-8e89-1d70c62edfed)

按照说明创建测试版应用，已关联测试企业，开启所有关于云文档的权限。
脚本运行时的信息：
`PS C:\Users\GeMaw\Desktop\feishu2mdtest> feishu2md https://a81isol8fe.feishu.cn/docx/ODBTdl5sMowg5zxwh2kcR6cQnKg
Captured document token: ODBTdl5sMowg5zxwh2kcR6cQnKg
Downloaded markdown file to ODBTdl5sMowg5zxwh2kcR6cQnKg.md`

麻烦大佬看看，感谢！

**Comment by xmsz** [comment]
> 没有人能够在仅凭两个截图就能定位问题；请提供更多的信息以供复现问题。
补充了 https://china.feishu.cn/docx/KvtddjWdqo6Jb3x20SpcevD5nnh

**Comment by Wsine** [comment]
@xmsz @JackiMa 我查看了你们俩各自提供的文档，发现文档中使用的 Block 类型均为 Sheet 而不是普通的 Table。

详见飞书文档结构：https://open.feishu.cn/document/server-docs/docs/docs/docx-v1/docx-structure#53fe05b8

本项目仅支持 markdown 格式可支持的简易 Table，请自行在飞书文档中将 Sheet 转换为 Table 再尝试下载。

**Comment by xmsz** [comment]
> @xmsz @JackiMa 我查看了你们俩各自提供的文档，发现文档中使用的 Block 类型均为 Sheet 而不是普通的 Table。
> 
> 详见飞书文档结构：https://open.feishu.cn/document/server-docs/docs/docs/docx-v1/docx-structure#53fe05b8
> 
> 本项目仅支持 markdown 格式可支持的简易 Table，请自行在飞书文档中将 Sheet 转换为 Table 再尝试下载。

那后面会支持这种类型吗

**Comment by Wsine** [comment]
> 那后面会支持这种类型吗

无法支持

**Comment by Wsine** [comment]
两周没有更新的回复，暂时关闭 issue，如仍有该问题，可重新打开
