### ISSUE TITLE
缺少 arm 平台的预编译可执行文件

### ISSUE THREAD

**Issue by Cococococococococococococo** [Wsine/feishu2md#8]
将feishu2md改为可执行状态后，运行直接killed，和系统有没有关系？我是macproM1

**Comment by Wsine** [comment]
M1 是 arm 处理器，我只预编译了 x86 架构的可执行文件。

我尝试了一下交叉编译 macOS arm 版本的，你可以帮忙下载看看能不能用吗？
下载链接：[feishu2md.zip](https://github.com/Wsine/feishu2md/files/9209115/feishu2md.zip)

还未压缩，文件比较大

**Comment by Cococococococococococococo** [comment]
大佬你好，我通过make指令自己成功的成功了feishu2md文件，指令现在是可用状态，config文件也可用。我碰到了个新的问题，目前正在尝试解决。。。你有什么思路吗，看上去获取飞书应用接口报错了。 [image]

**Comment by Wsine** [comment]
无法看到图片

**Comment by Cococococococococococococo** [comment]
我可以加你飞书or微信or钉钉or anyone ，目前可能需要依靠你的这个工具

**Comment by Wsine** [comment]
Issue 的问题需要在 Issue 中交流，这样方便遇到相同问题的后来者获得解答。

**Comment by Cococococococococococococo** [comment]
问题是这样的： 执行命令： @192 ~ % feishu2md https://vikadata.feishu.cn/docx/doxcnwkNuaSkNusCU8keuHSdj3e 报错： Captured doc token: doxcnwkNuaSkNusCU8keuHSdj3e 2022/07/28 20:03:03 request Auth#GetTenantAccessToken f

**Comment by Wsine** [comment]
检查一下 Token 的配置是否正确，我下载测试是正常的，本地文件已删除。

**Comment by Cococococococococococococo** [comment]
我用postman调用两个接口都是OK的，你说的token的问题是app的id设置还是doc的id

**Comment by Wsine** [comment]
很奇怪，但没有进一步的信息，我也很难说问题出在了哪里。

不如试试用 rosetta2 运行 x86 版本的确认一下或者用 linux 测试一下确保 config 相关的是正确的

**Comment by Wsine** [comment]
最新的 release 已更新全平台编译，因此关闭该 issue，如有问题再重新打开。
