### ISSUE TITLE
[Bug]: windows11 无法打开.exe执行文件

### ISSUE THREAD

**Issue by starr-starr** [Wsine/feishu2md#84]
### 问题描述

已添加解压地址至环境变量PATH内<br>
 打开.exe文件终端一闪而逝 再无任何反应

### 飞书文档链接

https://vdww5i5kjs.feishu.cn/docx/YOVRduoUSoPU4axW3q4clrwxnLc

### 期望的 markdown 格式

```markdown
# Title
```

**Comment by Wsine** [comment]
这里有一份教程说明如何在 Windows 环境下执行命令行程序

https://www.wikihow.com/Run-an-EXE-File-From-Command-Prompt

**Comment by starr-starr** [comment]
仍然是一闪而过，设置使用管理员身份也不行

**Comment by starr-starr** [comment]
仍然是一闪而过，设置使用管理员身份也不行

**Comment by Wsine** [comment]
我很确信这是一个很经典的对 exe 文件认识不足的问题。

抛开目前的先验知识，严格跟着教程操作，如果仍然有错，请录制该教程步骤会出错的情况

https://www.screentogif.com/

**Comment by starr-starr** [comment]
感谢！在该教程 (https://www.wikihow.com/Run-an-EXE-File-From-Command-Prompt) 的最后一步去掉 start 成功运行！祝你生活愉快
