### ISSUE TITLE
[Bug]:在线版本提示502

### ISSUE THREAD

**Issue by syyjay** [Wsine/feishu2md#85]
### 问题描述

您好，我想看下效果，以便更深的研究，但是在体验在线版本时，报502，这是链接：https://iqiq46fcl0h.feishu.cn/docx/OLs9dDrWzotPcnxR74hcFZsGn7b，麻烦帮忙看看，非常感谢

### 飞书文档链接

https://iqiq46fcl0h.feishu.cn/docx/OLs9dDrWzotPcnxR74hcFZsGn7b

### 期望的 markdown 格式

```markdown
能把文档复制过来即可
```

**Comment by Wsine** [comment]
502 Bad gateway 是不是看错了，我这里还能打开访问到前端网页

内部错误有两种可能
1）解析文档遇到一些 bug，这个需要你下载可执行文件本地复现
2）文檔里面包含大量的高清图片，超出了 Render 服务免费提供的 512M 的运行时限制

**Comment by Wsine** [comment]
超过一周没有新的回复，故暂时关闭，如仍有疑问可重新打开讨论。
