### ISSUE TITLE
[需求讨论] 恢复 Docs 支持

### ISSUE THREAD

**Issue by wy-z** [Wsine/feishu2md#86]
### 问题描述

飞书的用户群多为企业用户，积累下来文档中，应该有不少是旧版本，毕竟新旧版本对用户感知不明显，也不支持强制转换...
打算在 v2 上恢复 Docs 版本支持，公司存量比较多（可以帮忙维护）

@Wsine 你看是否合适～

### 飞书文档链接

暂无

### 期望的 markdown 格式

```markdown
暂无
```

**Comment by Wsine** [comment]
如果有大量的需求的话（更多的反馈在这个问题上），我是很乐意维护的，虽然会有一些困难，但这个可以讨论解决。

目前来说，docs 文档的下载可以通过 [v1.4.0](https://github.com/Wsine/feishu2md/releases/tag/v1.4.0) 的归档来处理，链接也写在了 README 文档中了。

> 毕竟新旧版本对用户感知不明显

这个我也同意，但如果只是缓解的话，可以在新版本中解析到 v1 文档链接的时候提供提示指向旧工具。

----

### doc 文档下载遇到问题怎么办

从飞书的角度的上来说，他们应该不会再更新 doc 文档的接口了。因此，我们工具的解析也不会新增太多的问题。如果只是小修小补，我感觉再发1~2个小版本，问题的数量也会收敛。

对于是否有必要从归档里转移到 active developing 是一个值得探讨的问题。

----

维护的困难其实有两方面

其一是后端的 parser 现在主要依据 hierarchical 的方式做解析的，这个在旧文档接口里不会提供，因此我理解必须是维护两套处理。

其二是前端目前做了 CLI 和 WEB 两个入口，除了捕获输入处理不同外，剩余调用逻辑很相近（还比较懒没有整理）。两套后端接口会加剧前端调用的多样性。

**Comment by wy-z** [comment]
如果继续支持旧版本的话，项目的入门、推广可能会更友好些～
比如 https://github.com/Wsine/feishu2md/issues/85 ，有没有可能用的就是旧版本 dock 的 url，目前旧版本应该会直接 panic ～
毕竟新旧版本，其实用户很难感知～

**Comment by Wsine** [comment]
如果什么都帮用户想得面面俱到，那这是赚钱的大公司的做法，不是用爱发电的开源项目的做法。

更何况，飞书项目组也没打算维护 v1 api，作为它的下游应用，feishu2md 其实没有理由费力地去维护过时的 api。

针对具体的问题，我更希望专注在具体的技术探讨上，而不是讨论各种可能的非法输入。

#85 使用 web 入口，而本身 feishu2md 的前端就有校验 URL 的功能。参考 https://github.com/Wsine/feishu2md/blob/34fb9a82432831ad1263ae047c9c79fe9c53c4aa/web/download.go#L28-L34

**Comment by wy-z** [comment]
> 如果什么都帮用户想得面面俱到，那这是赚钱的大公司的做法，不是用爱发电的开源项目的做法。
> 
> 更何况，飞书项目组也没打算维护 v1 api，作为它的下游应用，feishu2md 其实没有理由费力地去维护过时的 api。
> 
> 针对具体的问题，我更希望专注在具体的技术探讨上，而不是讨论各种可能的非法输入。
> 
> #85 使用 web 入口，而本身 feishu2md 的前端就有校验 URL 的功能。参考
> 
> https://github.com/Wsine/feishu2md/blob/34fb9a82432831ad1263ae047c9c79fe9c53c4aa/web/download.go#L28-L34

OK...这个不勉强
不过这里 wiki 取到的 docToken 可能是旧版 doc 的，应该还是会出问题 panic 之类的
