### ISSUE TITLE
[Bug]:  明明已经开通了阅读权限，但一直报错需要文档read only

### ISSUE THREAD

**Issue by catherine-lisa** [Wsine/feishu2md#87]
### 问题描述

![image](https://github.com/Wsine/feishu2md/assets/57988481/798d29e2-914d-40e8-b661-c7109e7d73cf)

已经配置好了应用和APPID，且需要转换的文档已经开启了互联网可阅读，但是执行的时候一直报错 One of the following scopes is required: [docx:document, docx:document:readonly]

### 飞书文档链接

https://f0naiapy4ad.feishu.cn/docx/F1cxdRqbro5qclxvDMGc9bUxnSb?from=from_copylink

### 期望的 markdown 格式

```markdown
# None, I could not transform.
```

**Comment by Wsine** [comment]
飞书后台配置的阅读权限有好几个选项，建议参考 https://github.com/Wsine/feishu2md/issues/41#issuecomment-1379755158 进行配置

**Comment by LegendBug** [comment]
你可能没有发布版本。在控制台的“版本管理与发布”里点创建版本
