### ISSUE TITLE
[Bug]: Invalid feishu/larksuite URL format

### ISSUE THREAD

**Issue by solar555** [Wsine/feishu2md#88]
### 问题描述

问题描述：
windows10环境
个人版的自建应用

错误：Invalid feishu/larksuite URL format
截图：
![4ec3725df38d66ff1d7a56e25048c43](https://github.com/Wsine/feishu2md/assets/18612729/16f09dec-971f-40d2-8bc6-d16f0a174ff3)

麻烦帮忙看一下问题，谢谢！

### 飞书文档链接

飞书链接：https://g5bxp4iqpk.feishu.cn/wiki/SGucwk9uXi0dFWkC6utcg1FnnSf?from=from_copylink

### 期望的 markdown 格式

```markdown
## Hello World
```

**Comment by Wsine** [comment]
大概是一个 bug，链接解析没有考虑到后面 url parameters 的问题。

目前解决方案：使用链接 `https://g5bxp4iqpk.feishu.cn/wiki/SGucwk9uXi0dFWkC6utcg1FnnSf` 下载。

**Comment by Wsine** [comment]
试试 `.\feishu2md "https://g5bxp4iqpk.feishu.cn/wiki/SGucwk9uXi0dFWkC6utcg1FnnSf?from=from_copylink"` 这样呢

**Comment by Wsine** [comment]
由于没有更多的回应，暂时关闭 issue
