### ISSUE TITLE
[问题]: 在您的网站下可以下载成功的wiki文档，但是本地下载报错

### ISSUE THREAD

**Issue by Zzhiter** [Wsine/feishu2md#89]
### 问题描述

![image](https://github.com/Wsine/feishu2md/assets/61727602/d4e73c26-f0e2-472f-a8a4-7e83b2cc27ea)
hello，我wiki知识库里的文档，已开启了权限，本地配置也已经成功，但是下载的时候，好像是报错没有wiki的阅读权限？
![image](https://github.com/Wsine/feishu2md/assets/61727602/97db5a6a-bb0f-4870-b797-4a672bc1d23b)
但是我通过网站下载成功了
![image](https://github.com/Wsine/feishu2md/assets/61727602/b8530be4-d591-4d70-9873-592bfca6bae0)

### 飞书文档链接

https://ifs1r08y70.feishu.cn/wiki/DxYhw3HpLiFwtckSHCdclIHSnab

### 期望的 markdown 格式

```markdown
问题在上面，感谢🤝
```

**Comment by tree1123** [comment]
请问解决了吗  我也遇到这个问题 wiki:wiki：readonly

**Comment by Zzhiter** [comment]
@tree1123 没解决，最后去作者提供的网站上成功了

**Comment by Wsine** [comment]
应该是 TOKEN 权限配置的问题，请再检查一下。测试网址中使用的是我个人的 TOKEN。

**Comment by ai408** [comment]
请问解决了吗？同样问题。

**Comment by ai408** [comment]
> @tree1123 没解决，最后去作者提供的网站上成功了

现在作者网站HTTP ERROR 502

**Comment by haledeng** [comment]
request Drive#GetDocxDocument failed: code: 1770002, msg: not found

====================

Report the following if it is a bug

panic: request Drive#GetDocxDocument failed: code: 1770002, msg: not found

**Comment by ai408** [comment]
我的已经解决了，把文档设置为互联网可访问就行了。

**Comment by Wsine** [comment]
由于没有更多的回应，暂时关闭 issue，如仍需讨论，可重开该 issue。

P.S., 在线版本可供交叉验证是否自己的 API Token 配置错误。
