### ISSUE TITLE
可以加一个导出高亮块的功能吗？ 

### ISSUE THREAD

**Issue by guigui0114** [Wsine/feishu2md#99]
### 问题描述

可以加一个导出高亮块的功能吗？真的很需要这个功能。
我看了另一个问答说 “这个仓库还是打算限定在 markdown 的基础语法上”，

但是我经常用高亮文字背景来代替Head，因为head层级太多的话，笔记就不够扁平，梳理思路的时候脑子会很混乱。
如果用 bold 或者 underline 效果就没那么好，
就像 head 只能改变文字的大小，这两种效果也都没有“很强的视觉效果”，
加入颜色真的能有效的帮助笔记结构的梳理。

求求了求求了，可以吗/(ㄒoㄒ)/~~

还有我用了 v2.1.0，为啥不能输出到指定路径？还是默认下载到administrator？

![1](https://github.com/Wsine/feishu2md/assets/125194895/a9a5e437-68f5-4dae-a027-e43ef3c56007)

### 飞书文档链接

无

### 期望的 markdown 格式

```markdown
# 使用`<span style>`标签来定义文字**背景**高亮颜色
<span style="background-color: #F2F3F5">背景高亮为浅灰色的文字。</span>
<span style="background-color: #FBBFBC">背景高亮为浅红色的文字。</span>
<span style="background-color: #FEDDB6">背景高亮为浅橙色的文字。</span>
<span style="background-color: #FEF794">背景高亮为浅黄色的文字。</span>
<span style="background-color: #C3EEC0">背景高亮为浅绿色的文字。</span>
<span style="background-color: #CDDAFB">背景高亮为浅蓝色的文字。</span>
<span style="background-color: #DCC9FB">背景高亮为浅紫色的文字。</span>
<span style="background-color: #E5E6E9">背景高亮为中灰色的文字。</span>
<span style="background-color: #BBBFC4">背景高亮为深灰色的文字。</span>
<span style="background-color: #F76964">背景高亮为红色的文字。</span>
<span style="background-color: #FFA53D">背景高亮为橙色的文字。</span>
<span style="background-color: #FFE928">背景高亮为黄色的文字。</span>
<span style="background-color: #62D256">背景高亮为绿色的文字。</span>
<span style="background-color: #9EBBFE">背景高亮为蓝色的文字。</span>
<span style="background-color: #C4A4FA">背景高亮为紫色的文字。</span>

# `<span style>`标签来定义文字颜色
<span style="color: #D5D7DA;">这是灰色的字体。</span>
<span style="color: #DB4F48;">这是红色的字体。</span>
<span style="color: #E28922;">这是橙色的字体。</span>
<span style="color: #DDA011;">这是黄色的字体。</span>
<span style="color: #3DA731;">这是绿色的字体。</span>
<span style="color: #4372DE;">这是蓝色的字体。</span>
<span style="color: #6B31CB;">这是紫色的字体。</span>
```

**Comment by Wsine** [comment]
> 我看了另一个问答说 “这个仓库还是打算限定在 markdown 的基础语法上”，

是的，如无更多的讨论支持，我想还是保留简洁比较好。

> 还有我用了 v2.1.0，为啥不能输出到指定路径？还是默认下载到administrator？

请参照 README 命令格式。如仍有疑问，请将你的命令 post 在这里。

P.S., 不同的问题请分开不同的 issue 进行讨论

**Comment by Wsine** [comment]
两周没有新的回复，暂时关闭 issue

**Comment by ZhengshuaiPENG** [comment]
对于这个功能想 +1，高亮块的使用在文档中非常频繁，如果能通过css的方式来支持在 markdown 中渲染就最好了

**Comment by Lightblues** [comment]
同求! 

语法可以参考
1. mkdocs 中的 Admonitions 标记, 语法是 `!!! note`, 参见 [doc](https://squidfunk.github.io/mkdocs-material/reference/admonitions/), 也是vscode插件 Markdown Preview Enhanced 支持的语法 [doc](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/markdown-basics?id=%e6%89%a9%e5%b1%95%e7%9a%84%e8%af%ad%e6%b3%95)
2. 标记, 语法是 `> [!NOTE] `, GitHub已经支持, 参见 [issue](https://github.com/orgs/community/discussions/16925)

两种语法的格式:

```
=== 第一种 ===
!!! note
    xxx

=== 第二种 ===
> [!NOTE]  
> xxx
```


GitHub中使用第二种的展示:

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.

**Comment by guigui0114** [comment]
> 同求!
> 
> 语法可以参考
> 
> 1. mkdocs 中的 Admonitions 标记, 语法是 `!!! note`, 参见 [doc](https://squidfunk.github.io/mkdocs-material/reference/admonitions/), 也是vscode插件 Markdown Preview Enhanced 支持的语法 [doc](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/markdown-basics?id=%e6%89%a9%e5%b1%95%e7%9a%84%e8%af%ad%e6%b3%95)
> 2. 标记, 语法是 `> [!NOTE] `, GitHub已经支持, 参见 [issue](https://github.com/orgs/community/discussions/16925)
> 
> 两种语法的格式:
> 
> ```
> === 第一种 ===
> !!! note
>     xxx
> 
> === 第二种 ===
> > [!NOTE]  
> > xxx
> ```
> 
> GitHub中使用第二种的展示:
> 
> Note
> 
> Highlights information that users should take into account, even when skimming.
> 
> Tip
> 
> Optional information to help a user be more successful.
> 
> Important
> 
> Crucial information necessary for users to succeed.
> 
> Warning
> 
> Critical content demanding immediate user attention due to potential risks.
> 
> Caution
> 
> Negative potential consequences of an action.

你说的这个高亮块好像跟我的诉求不是一个东西，你这个是callout吧，我是想在文字上加高亮的底色，划线高亮那样。我这个诉求有其他插件能实现了，不过我觉得你提的这个也很香。

**Comment by ZhaoXiangXML** [comment]
@guigui0114 “别的插件”是指什么？我试了几个都不太好用

**Comment by guigui0114** [comment]
> @guigui0114 “别的插件”是指什么？我试了几个都不太好用

feishu-backup。啊啊啊我有罪，我不是来砸场子的，各有各的好，但是我真的很需要文字高亮/(ㄒoㄒ)/~~

**Comment by Wsine** [comment]
我刚刚合并了一个新的 PR，see https://github.com/Wsine/feishu2md/pull/133 或许能满足你的需求

**Comment by Wsine** [comment]
#133 已合并和发布，故关闭此issue
